# Step19_current78: Compute pig early signature scores from current 78-derived pig signature genes using TMM-normalized logCPM
# Purpose:
# This corrected Step19 computes pig early signature scores using the current78-derived pig signature gene table
# generated by Step18_current78. Compared with the earlier CPM-only implementation, this version uses the
# full gene-level count matrix to estimate edgeR TMM normalization factors and then calculates TMM-normalized
# logCPM values before extracting the 75 signature genes and applying gene-wise z-score standardization.
# It saves score matrices, group comparison statistics, Figure4A score plots, full logs, a short summary log
# for review, software/session records, input audits, normalization factors, and archived copies of this script.
#
# Primary score definition:
# directional_score = (sum(z_up) + sum(-z_down)) / (n_up + n_down)
# For audit/backward comparison, an unweighted sum-of-means directional score is also saved:
# directional_score_sum_means = up_score + down_score_reoriented
#
# Important methodological note:
# No filterByExpr() filtering is applied before signature scoring so that all Step18-detected signature genes
# remain eligible for scoring. TMM normalization factors are estimated from the full Step16 gene-level count matrix.

## =========================
## 0. Basic settings
## =========================

base_dir <- "E:/R/ACLsenescence2/rebuild_submission/02_pig_early"

tables_dir <- file.path(base_dir, "tables")
logs_dir <- file.path(base_dir, "logs")
scripts_dir <- file.path(base_dir, "scripts")
figures_dir <- file.path(base_dir, "figures", "Figure4A_current78")

out_dir <- file.path(tables_dir, "step19_current78_pig_signature_score")
out_log_dir <- file.path(out_dir, "logs")
out_script_dir <- file.path(out_dir, "scripts")

## Remove previous Step19 outputs before rerun to avoid mixing the older CPM-only outputs with this corrected TMM-logCPM run.
if (dir.exists(out_dir)) unlink(out_dir, recursive = TRUE, force = TRUE)
if (dir.exists(figures_dir)) unlink(list.files(figures_dir, full.names = TRUE, recursive = TRUE), recursive = TRUE, force = TRUE)

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(out_log_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(out_script_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(logs_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(scripts_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

full_log_file <- file.path(out_log_dir, "step19_current78_pig_signature_score_full_log.txt")
summary_log_file <- file.path(out_log_dir, "step19_current78_pig_signature_score_summary_to_send_me.txt")
full_log_project_copy <- file.path(logs_dir, "step19_current78_pig_signature_score_full_log.txt")
summary_log_project_copy <- file.path(logs_dir, "step19_current78_pig_signature_score_summary_to_send_me.txt")

sink(full_log_file, split = TRUE)

cat("===== STEP19_CURRENT78 PIG EARLY SIGNATURE SCORE: TMM LOGCPM CORRECTED VERSION =====\n")
cat("Run time: ", format(Sys.time()), "\n", sep = "")
cat("Base directory: ", base_dir, "\n", sep = "")
cat("Expression input: TMM-normalized logCPM from full Step16 count matrix using edgeR::calcNormFactors(method = 'TMM').\n")
cat("Primary score: combined weighted directional score = (sum up z + sum -down z)/(n_up+n_down).\n")
cat("Audit score: directional_score_sum_means = up_score + down_score_reoriented.\n\n")

if (!requireNamespace("edgeR", quietly = TRUE)) {
  stop("Package 'edgeR' is required for this corrected TMM-normalized Step19 script. Please install edgeR and rerun.", call. = FALSE)
}

## =========================
## 1. Helper functions
## =========================

stop_if_missing <- function(file, label) {
  if (!file.exists(file)) stop("Missing ", label, ": ", file, call. = FALSE)
}

clean_string <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null", "None", "none")] <- NA_character_
  x
}

safe_read_csv <- function(file) read.csv(file, stringsAsFactors = FALSE, check.names = FALSE)

first_existing_col <- function(df, candidates, label) {
  hit <- intersect(candidates, colnames(df))
  if (length(hit) == 0) {
    stop("Could not find column for ", label, ". Checked: ", paste(candidates, collapse = ", "),
         "\nAvailable columns: ", paste(colnames(df), collapse = ", "), call. = FALSE)
  }
  hit[1]
}

guess_sample_col <- function(manifest, count_sample_cols) {
  best_col <- NA_character_; best_n <- -1L
  for (cc in colnames(manifest)) {
    vals <- clean_string(manifest[[cc]])
    n_match <- sum(vals %in% count_sample_cols, na.rm = TRUE)
    if (n_match > best_n) { best_n <- n_match; best_col <- cc }
  }
  if (is.na(best_col) || best_n == 0) {
    stop("Could not identify sample ID column in manifest by matching count matrix sample columns.\n",
         "Count matrix samples preview: ", paste(head(count_sample_cols, 10), collapse = ", "),
         "\nManifest columns: ", paste(colnames(manifest), collapse = ", "), call. = FALSE)
  }
  best_col
}

guess_group_col <- function(manifest, sample_col) {
  candidates <- setdiff(colnames(manifest), sample_col)
  best_col <- NA_character_; best_score <- -1L
  for (cc in candidates) {
    vals <- clean_string(manifest[[cc]])
    vals_low <- tolower(vals)
    score <- sum(grepl("control|ctrl|contra|t0|aclt|acl|transection|untreated|t7|t28|1w|4w|week", vals_low), na.rm = TRUE)
    unique_n <- length(unique(vals[!is.na(vals)]))
    if (unique_n > max(10, nrow(manifest) * 0.8)) score <- score - unique_n
    if (score > best_score) { best_score <- score; best_col <- cc }
  }
  if (is.na(best_col) || best_score <= 0) {
    stop("Could not identify group column in manifest. Please check manifest columns: ",
         paste(colnames(manifest), collapse = ", "), call. = FALSE)
  }
  best_col
}

normalize_pig_group <- function(x) {
  z <- tolower(clean_string(x))
  out <- rep(NA_character_, length(z))
  out[grepl("control|ctrl|sham|normal|t0", z)] <- "Control"
  out[grepl("t7|7d|7 day|7_day|1w|1 week|1_week", z) & grepl("acl|transection|untreated|aclt", z)] <- "ACLT_t7"
  out[grepl("t28|28d|28 day|28_day|4w|4 week|4_week", z) & grepl("acl|transection|untreated|aclt", z)] <- "ACLT_t28"
  out[is.na(out) & grepl("t7|7d|7 day|7_day|1w|1 week|1_week", z)] <- "ACLT_t7"
  out[is.na(out) & grepl("t28|28d|28 day|28_day|4w|4 week|4_week", z)] <- "ACLT_t28"
  out
}

row_z <- function(mat) {
  m <- rowMeans(mat, na.rm = TRUE)
  s <- apply(mat, 1, sd, na.rm = TRUE)
  z <- sweep(mat, 1, m, "-")
  z <- sweep(z, 1, s, "/")
  z[!is.finite(z)] <- NA_real_
  z
}

write_csv <- function(x, file) {
  write.csv(x, file, row.names = FALSE, quote = TRUE)
  cat("Saved: ", file, "\n", sep = "")
}
write_matrix_csv <- function(mat, file) {
  write.csv(mat, file, quote = TRUE)
  cat("Saved: ", file, "\n", sep = "")
}

get_script_path <- function() {
  cmd_args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", cmd_args, value = TRUE)
  if (length(file_arg) > 0) return(normalizePath(sub("^--file=", "", file_arg[1]), winslash = "/", mustWork = FALSE))
  NA_character_
}
file_md5_safe <- function(file) {
  if (!file.exists(file)) return(NA_character_)
  if (requireNamespace("tools", quietly = TRUE)) return(as.character(tools::md5sum(file)))
  NA_character_
}

## =========================
## 2. Define input files
## =========================

signature_file <- file.path(tables_dir, "step18_current78_pig_early_signature_remap", "step18_current78_pig_signature_gene_table.csv")
count_file <- file.path(tables_dir, "step16_pig_early_gene_count_matrix.csv")
manifest_file <- file.path(tables_dir, "step09_pig_early_core_sample_fastq_manifest.csv")

stop_if_missing(signature_file, "Step18 current78 pig signature gene table")
stop_if_missing(count_file, "pig early Step16 gene count matrix")
stop_if_missing(manifest_file, "pig early core sample manifest")

cat("Input signature file: ", signature_file, "\n", sep = "")
cat("Input count matrix: ", count_file, "\n", sep = "")
cat("Input sample manifest: ", manifest_file, "\n\n", sep = "")

## =========================
## 3. Load data
## =========================

sig_df <- safe_read_csv(signature_file)
count_df <- safe_read_csv(count_file)
manifest <- safe_read_csv(manifest_file)

pig_ensg_col <- first_existing_col(sig_df, c("pig_ensg", "pig_gene_id", "pig_gene", "gene_id"), "pig Ensembl gene ID")
direction_col <- first_existing_col(sig_df, c("signature_direction", "mouse_direction", "direction"), "signature direction")

sig_df[[pig_ensg_col]] <- clean_string(sig_df[[pig_ensg_col]])
sig_df[[direction_col]] <- clean_string(sig_df[[direction_col]])
sig_df <- sig_df[!is.na(sig_df[[pig_ensg_col]]) & !is.na(sig_df[[direction_col]]), , drop = FALSE]
sig_df <- sig_df[!duplicated(sig_df[[pig_ensg_col]]), , drop = FALSE]

up_genes <- sig_df[[pig_ensg_col]][sig_df[[direction_col]] == "Up_in_ACLR"]
down_genes <- sig_df[[pig_ensg_col]][sig_df[[direction_col]] == "Down_in_ACLR"]
if (length(up_genes) == 0 || length(down_genes) == 0) stop("Signature gene table must contain both Up_in_ACLR and Down_in_ACLR genes.", call. = FALSE)

cat("Loaded signature genes: ", nrow(sig_df), "\n", sep = "")
cat("Up genes: ", length(up_genes), "\n", sep = "")
cat("Down genes: ", length(down_genes), "\n\n", sep = "")

if (nrow(sig_df) != 75 || length(up_genes) != 65 || length(down_genes) != 10) {
  stop("Unexpected current78 signature size. Expected total/up/down = 75/65/10, but observed ",
       nrow(sig_df), "/", length(up_genes), "/", length(down_genes),
       ". Please re-check Step18 outputs before scoring.", call. = FALSE)
}

## =========================
## 4. Prepare count matrix and sample metadata
## =========================

gene_col <- first_existing_col(count_df, c("gene_id", "Geneid", "gene", "pig_ensg"), "count matrix gene ID")
count_df[[gene_col]] <- clean_string(count_df[[gene_col]])
sample_cols <- setdiff(colnames(count_df), gene_col)
numeric_sample_cols <- sample_cols[sapply(count_df[sample_cols], function(x) suppressWarnings(all(is.na(x) | !is.na(as.numeric(x)))))]
if (length(numeric_sample_cols) == 0) stop("No numeric sample columns detected in count matrix.", call. = FALSE)
sample_cols <- numeric_sample_cols

count_mat <- as.matrix(data.frame(lapply(count_df[, sample_cols, drop = FALSE], function(x) as.numeric(as.character(x))), check.names = FALSE))
rownames(count_mat) <- count_df[[gene_col]]
valid_rows <- !is.na(rownames(count_mat)) & rownames(count_mat) != ""
count_mat <- count_mat[valid_rows, , drop = FALSE]
count_mat <- count_mat[!duplicated(rownames(count_mat)), , drop = FALSE]
if (anyNA(count_mat)) stop("NA values detected in the count matrix after numeric conversion.", call. = FALSE)
if (any(count_mat < 0, na.rm = TRUE)) stop("Negative count values detected in the count matrix.", call. = FALSE)

sample_col <- guess_sample_col(manifest, colnames(count_mat))
group_col <- guess_group_col(manifest, sample_col)
manifest$sample_id_for_count <- clean_string(manifest[[sample_col]])
manifest$group_raw_for_count <- clean_string(manifest[[group_col]])
manifest$group_current78 <- normalize_pig_group(manifest$group_raw_for_count)
manifest2 <- manifest[manifest$sample_id_for_count %in% colnames(count_mat), , drop = FALSE]
manifest2 <- manifest2[match(colnames(count_mat), manifest2$sample_id_for_count), , drop = FALSE]
if (any(is.na(manifest2$sample_id_for_count))) stop("Some count matrix sample columns cannot be matched to manifest.", call. = FALSE)
if (any(is.na(manifest2$group_current78))) {
  bad <- manifest2[is.na(manifest2$group_current78), c("sample_id_for_count", "group_raw_for_count"), drop = FALSE]
  write_csv(bad, file.path(out_dir, "step19_current78_unresolved_sample_groups.csv"))
  stop("Some sample groups could not be normalized. See step19_current78_unresolved_sample_groups.csv", call. = FALSE)
}
expected_groups <- c("Control", "ACLT_t7", "ACLT_t28")
if (!all(expected_groups %in% manifest2$group_current78)) {
  stop("Not all expected groups were detected. Expected: ", paste(expected_groups, collapse = ", "),
       "\nObserved: ", paste(unique(manifest2$group_current78), collapse = ", "), call. = FALSE)
}
count_mat <- count_mat[, manifest2$sample_id_for_count, drop = FALSE]

cat("Detected sample ID column in manifest: ", sample_col, "\n", sep = "")
cat("Detected group column in manifest: ", group_col, "\n", sep = "")
cat("Group counts:\n")
print(table(manifest2$group_current78))
cat("\n")

## =========================
## 5. Match signature genes and compute TMM-normalized logCPM/z-scores
## =========================

missing_sig <- sig_df[!(sig_df[[pig_ensg_col]] %in% rownames(count_mat)), , drop = FALSE]
if (nrow(missing_sig) > 0) {
  write_csv(missing_sig, file.path(out_dir, "step19_current78_signature_genes_missing_in_count_matrix.csv"))
  stop("Some Step18 current78 signature genes are missing in the Step16 count matrix. See output file.", call. = FALSE)
}

sig_order <- sig_df[[pig_ensg_col]]
lib_size <- colSums(count_mat, na.rm = TRUE)
if (any(lib_size <= 0 | !is.finite(lib_size))) stop("Invalid library sizes detected.", call. = FALSE)

## Estimate TMM normalization factors from the full Step16 count matrix, then extract signature genes.
## No filterByExpr() filtering is applied before scoring so that all Step18-detected signature genes remain included.
dge <- edgeR::DGEList(counts = count_mat)
dge <- edgeR::calcNormFactors(dge, method = "TMM")
logcpm_all <- edgeR::cpm(dge, log = TRUE, prior.count = 1, normalized.lib.sizes = TRUE)
logcpm_mat <- logcpm_all[sig_order, , drop = FALSE]

norm_factor_df <- data.frame(
  sample_id = colnames(count_mat),
  group = manifest2$group_current78,
  raw_library_size = as.numeric(dge$samples$lib.size),
  TMM_norm_factor = as.numeric(dge$samples$norm.factors),
  effective_library_size = as.numeric(dge$samples$lib.size * dge$samples$norm.factors),
  stringsAsFactors = FALSE
)

z_mat <- row_z(logcpm_mat)
if (anyNA(z_mat)) {
  na_rows <- rownames(z_mat)[apply(is.na(z_mat), 1, any)]
  write.csv(data.frame(pig_ensg = na_rows), file.path(out_dir, "step19_current78_signature_genes_with_NA_zscore.csv"), row.names = FALSE)
  stop("NA z-scores detected for some signature genes, usually due to zero variance after TMM-normalized logCPM transformation. See output file.", call. = FALSE)
}

up_idx <- sig_df[[direction_col]] == "Up_in_ACLR"
down_idx <- sig_df[[direction_col]] == "Down_in_ACLR"
up_score <- colMeans(z_mat[up_idx, , drop = FALSE])
down_score_raw <- colMeans(z_mat[down_idx, , drop = FALSE])
down_score_reoriented <- -down_score_raw
directional_score <- colSums(rbind(z_mat[up_idx, , drop = FALSE], -z_mat[down_idx, , drop = FALSE])) / nrow(z_mat)
directional_score_sum_means <- up_score + down_score_reoriented
total_score_unoriented <- colMeans(z_mat)

scores_df <- data.frame(
  sample_id = colnames(z_mat),
  group = manifest2$group_current78,
  group_raw = manifest2$group_raw_for_count,
  total_score_unoriented = as.numeric(total_score_unoriented),
  up_score = as.numeric(up_score),
  down_score_raw = as.numeric(down_score_raw),
  down_score_reoriented = as.numeric(down_score_reoriented),
  directional_score = as.numeric(directional_score),
  directional_score_sum_means = as.numeric(directional_score_sum_means),
  stringsAsFactors = FALSE
)
scores_df$group <- factor(scores_df$group, levels = c("Control", "ACLT_t7", "ACLT_t28"))
scores_df <- scores_df[order(scores_df$group, scores_df$sample_id), , drop = FALSE]

## =========================
## 6. Group comparisons
## =========================

score_cols <- c("directional_score", "directional_score_sum_means", "up_score", "down_score_reoriented", "down_score_raw", "total_score_unoriented")
compare_one <- function(df, score_col, case_group) {
  control_vals <- df[df$group == "Control", score_col]
  case_vals <- df[df$group == case_group, score_col]
  wt <- wilcox.test(case_vals, control_vals, exact = FALSE, alternative = "two.sided")
  data.frame(
    comparison = paste0(case_group, "_vs_Control"),
    score = score_col,
    n_control = length(control_vals),
    n_case = length(case_vals),
    median_control = median(control_vals, na.rm = TRUE),
    median_case = median(case_vals, na.rm = TRUE),
    mean_control = mean(control_vals, na.rm = TRUE),
    mean_case = mean(case_vals, na.rm = TRUE),
    median_difference_case_minus_control = median(case_vals, na.rm = TRUE) - median(control_vals, na.rm = TRUE),
    mean_difference_case_minus_control = mean(case_vals, na.rm = TRUE) - mean(control_vals, na.rm = TRUE),
    wilcox_p_value = as.numeric(wt$p.value),
    stringsAsFactors = FALSE
  )
}
stats_df <- do.call(rbind, lapply(score_cols, function(sc) rbind(compare_one(scores_df, sc, "ACLT_t7"), compare_one(scores_df, sc, "ACLT_t28"))))
stats_df$BH_FDR_across_all_score_comparisons <- p.adjust(stats_df$wilcox_p_value, method = "BH")

## =========================
## 7. Long table and mouse-style Figure4A plots
## =========================

score_cols <- c("directional_score", "directional_score_sum_means", "up_score", "down_score_reoriented", "down_score_raw", "total_score_unoriented")
scores_long <- do.call(rbind, lapply(score_cols, function(sc) {
  data.frame(
    sample_id = scores_df$sample_id,
    group = as.character(scores_df$group),
    score_name = sc,
    score_value = scores_df[[sc]],
    stringsAsFactors = FALSE
  )
}))

## Plot only the three manuscript-relevant scores in Figure4A.
score_plot_levels <- c("directional_score", "up_score", "down_score_reoriented")
score_plot_labels <- c(
  directional_score = "Directional score",
  up_score = "Up-score",
  down_score_reoriented = "Down-score reoriented"
)
plot_long <- scores_long[scores_long$score_name %in% score_plot_levels, , drop = FALSE]
plot_long$score_label <- factor(score_plot_labels[plot_long$score_name], levels = unname(score_plot_labels[score_plot_levels]))
plot_long$group <- factor(plot_long$group, levels = c("Control", "ACLT_t7", "ACLT_t28"))

stats_plot <- stats_df[stats_df$score %in% score_plot_levels & stats_df$comparison %in% c("ACLT_t7_vs_Control", "ACLT_t28_vs_Control"), , drop = FALSE]
stats_plot$score_label <- factor(score_plot_labels[stats_plot$score], levels = unname(score_plot_labels[score_plot_levels]))
stats_plot$x <- ifelse(stats_plot$comparison == "ACLT_t7_vs_Control", 2, 3)
stats_plot$xend <- stats_plot$x
stats_plot$xmid <- stats_plot$x
stats_plot$group_label <- ifelse(stats_plot$comparison == "ACLT_t7_vs_Control", "ACLT_t7", "ACLT_t28")
fmt_p <- function(p) {
  ifelse(is.na(p), "p = NA", ifelse(p < 0.001, "p < 0.001", paste0("p = ", formatC(p, format = "f", digits = 3))))
}
stats_plot$p_label <- fmt_p(stats_plot$wilcox_p_value)
## Put p labels slightly above each score facet.
y_ranges <- aggregate(score_value ~ score_label, plot_long, function(x) diff(range(x, na.rm = TRUE)))
y_max <- aggregate(score_value ~ score_label, plot_long, max, na.rm = TRUE)
y_pos <- merge(y_max, y_ranges, by = "score_label")
colnames(y_pos) <- c("score_label", "y_max", "y_range")
y_pos$y_range[!is.finite(y_pos$y_range) | y_pos$y_range == 0] <- 1
stats_plot <- merge(stats_plot, y_pos, by = "score_label", all.x = TRUE)
stats_plot$y_label <- stats_plot$y_max + ifelse(stats_plot$group_label == "ACLT_t7", 0.10, 0.22) * stats_plot$y_range
stats_plot$y_segment <- stats_plot$y_max + ifelse(stats_plot$group_label == "ACLT_t7", 0.05, 0.17) * stats_plot$y_range

plot_files <- data.frame(plot = character(), file = character(), stringsAsFactors = FALSE)
if (requireNamespace("ggplot2", quietly = TRUE)) {
  library(ggplot2)

  ## Mouse Figure3A-inspired style: theme_bw, light grey grid, white control points,
  ## orange ACLT points, and p-value labels. There are no pair lines because pig early
  ## Control/ACLT_t7/ACLT_t28 are independent groups rather than paired sides.
  point_fill <- c(Control = "white", ACLT_t7 = "#D95F02", ACLT_t28 = "#E69F00")
  point_edge <- c(Control = "#7A7A7A", ACLT_t7 = "#7F3300", ACLT_t28 = "#8A5A00")

  p_combined <- ggplot(plot_long, aes(x = group, y = score_value)) +
    geom_point(
      aes(fill = group, color = group),
      shape = 21,
      stroke = 0.55,
      size = 3.1,
      position = position_jitter(width = 0.08, height = 0, seed = 1),
      alpha = 0.95
    ) +
    stat_summary(
      fun = median,
      geom = "crossbar",
      width = 0.44,
      linewidth = 0.35,
      color = "black"
    ) +
    geom_segment(
      data = stats_plot,
      aes(x = 1, xend = xend, y = y_segment, yend = y_segment),
      inherit.aes = FALSE,
      color = "#666666",
      linewidth = 0.35
    ) +
    geom_text(
      data = stats_plot,
      aes(x = xmid, y = y_label, label = p_label),
      inherit.aes = FALSE,
      size = 4.0
    ) +
    facet_grid(rows = vars(score_label), switch = "y", scales = "free_y") +
    scale_fill_manual(values = point_fill) +
    scale_color_manual(values = point_edge) +
    labs(
      title = "Current78-derived pig early signature scores (TMM logCPM)",
      x = NULL,
      y = "Mean row-z signature score"
    ) +
    theme_bw(base_size = 15) +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold", size = 19),
      panel.grid.major = element_line(color = "#E6E6E6"),
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = "#F0F0F0", color = "black"),
      strip.text = element_text(size = 13),
      strip.text.y.left = element_text(angle = -90, size = 13),
      axis.text.x = element_text(size = 12, angle = 20, hjust = 1),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size = 15),
      legend.position = "none"
    )

  combined_png <- file.path(figures_dir, "Figure4A_current78_signature_scores_mouse_style.png")
  combined_pdf <- file.path(figures_dir, "Figure4A_current78_signature_scores_mouse_style.pdf")
  ggsave(combined_png, p_combined, width = 7.4, height = 9.2, dpi = 320)
  ggsave(combined_pdf, p_combined, width = 7.4, height = 9.2)
  plot_files <- rbind(plot_files, data.frame(plot = "Figure4A_current78_signature_scores_mouse_style", file = combined_png, stringsAsFactors = FALSE))
  plot_files <- rbind(plot_files, data.frame(plot = "Figure4A_current78_signature_scores_mouse_style", file = combined_pdf, stringsAsFactors = FALSE))
  cat("Saved plot: ", combined_png, "\n", sep = "")
  cat("Saved plot: ", combined_pdf, "\n", sep = "")

  ## Also save one panel per score with the same visual style for flexible layout.
  for (sc in score_plot_levels) {
    dfp <- plot_long[plot_long$score_name == sc, , drop = FALSE]
    stp <- stats_plot[as.character(stats_plot$score_label) == score_plot_labels[[sc]], , drop = FALSE]
    p_one <- ggplot(dfp, aes(x = group, y = score_value)) +
      geom_point(aes(fill = group, color = group), shape = 21, stroke = 0.55, size = 3.1,
                 position = position_jitter(width = 0.08, height = 0, seed = 1), alpha = 0.95) +
      stat_summary(fun = median, geom = "crossbar", width = 0.44, linewidth = 0.35, color = "black") +
      geom_segment(data = stp, aes(x = 1, xend = xend, y = y_segment, yend = y_segment), inherit.aes = FALSE, color = "#666666", linewidth = 0.35) +
      geom_text(data = stp, aes(x = xmid, y = y_label, label = p_label), inherit.aes = FALSE, size = 4.0) +
      scale_fill_manual(values = point_fill) +
      scale_color_manual(values = point_edge) +
      labs(title = score_plot_labels[[sc]], x = NULL, y = "Mean row-z signature score") +
      theme_bw(base_size = 15) +
      theme(
        plot.title = element_text(hjust = 0.5, face = "bold", size = 18),
        panel.grid.major = element_line(color = "#E6E6E6"),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 12, angle = 20, hjust = 1),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 15),
        legend.position = "none"
      )
    safe_name <- gsub("[^A-Za-z0-9]+", "_", sc)
    png_file <- file.path(figures_dir, paste0("Figure4A_current78_", safe_name, "_mouse_style.png"))
    pdf_file <- file.path(figures_dir, paste0("Figure4A_current78_", safe_name, "_mouse_style.pdf"))
    ggsave(png_file, p_one, width = 5.4, height = 4.8, dpi = 320)
    ggsave(pdf_file, p_one, width = 5.4, height = 4.8)
    plot_files <- rbind(plot_files, data.frame(plot = paste0("Figure4A_current78_", safe_name, "_mouse_style"), file = png_file, stringsAsFactors = FALSE))
    plot_files <- rbind(plot_files, data.frame(plot = paste0("Figure4A_current78_", safe_name, "_mouse_style"), file = pdf_file, stringsAsFactors = FALSE))
    cat("Saved plot: ", png_file, "\n", sep = "")
    cat("Saved plot: ", pdf_file, "\n", sep = "")
  }
}

## =========================
## 8. Save outputs
## =========================

sig_meta <- sig_df
sig_meta$used_for_step19_current78_score <- TRUE
write_csv(sig_meta, file.path(out_dir, "step19_current78_pig_signature_gene_metadata.csv"))
write_matrix_csv(logcpm_mat, file.path(out_dir, "step19_current78_pig_signature_TMM_logCPM_matrix.csv"))
## Backward-compatible alias; content is TMM-normalized logCPM in this corrected script.
write_matrix_csv(logcpm_mat, file.path(out_dir, "step19_current78_pig_signature_logCPM_matrix.csv"))
write_matrix_csv(z_mat, file.path(out_dir, "step19_current78_pig_signature_zscore_matrix.csv"))
write_csv(norm_factor_df, file.path(out_dir, "step19_current78_TMM_normalization_factors.csv"))
write_csv(scores_df, file.path(out_dir, "step19_current78_pig_signature_scores_by_sample.csv"))
write_csv(scores_long, file.path(out_dir, "step19_current78_pig_signature_scores_long.csv"))
write_csv(stats_df, file.path(out_dir, "step19_current78_pig_signature_score_group_comparisons.csv"))
write_csv(manifest2, file.path(out_dir, "step19_current78_sample_metadata_used.csv"))

input_audit <- data.frame(
  label = c("Step18 current78 signature table", "Step16 pig early count matrix", "Step09 sample manifest"),
  file = c(signature_file, count_file, manifest_file),
  exists = c(file.exists(signature_file), file.exists(count_file), file.exists(manifest_file)),
  size_bytes = c(file.info(signature_file)$size, file.info(count_file)$size, file.info(manifest_file)$size),
  mtime = as.character(c(file.info(signature_file)$mtime, file.info(count_file)$mtime, file.info(manifest_file)$mtime)),
  md5 = c(file_md5_safe(signature_file), file_md5_safe(count_file), file_md5_safe(manifest_file)),
  stringsAsFactors = FALSE
)
write_csv(input_audit, file.path(out_dir, "step19_current78_input_file_audit.csv"))

run_summary <- data.frame(
  metric = c(
    "signature_input_file", "count_matrix_file", "manifest_file",
    "n_signature_genes_used", "n_up_signature_genes", "n_down_signature_genes",
    "n_samples", "n_Control", "n_ACLT_t7", "n_ACLT_t28",
    "score_scale", "normalization_method", "filtering_before_score",
    "primary_directional_score_definition", "audit_directional_score_sum_means_saved",
    "group_test", "multiple_testing_correction", "main_score_table", "group_comparison_table",
    "TMM_logCPM_matrix", "TMM_normalization_factor_table", "output_dir"
  ),
  value = c(
    signature_file, count_file, manifest_file,
    nrow(sig_df), length(up_genes), length(down_genes),
    nrow(scores_df), sum(scores_df$group == "Control"), sum(scores_df$group == "ACLT_t7"), sum(scores_df$group == "ACLT_t28"),
    "TMM-normalized logCPM, then row-wise z-score across 18 samples",
    "edgeR::DGEList(full Step16 count matrix) -> edgeR::calcNormFactors(method = 'TMM') -> edgeR::cpm(log = TRUE, prior.count = 1, normalized.lib.sizes = TRUE)",
    "No filterByExpr() filtering before signature scoring; all Step18-detected signature genes are retained",
    "(sum up z + sum -down z)/(n_up+n_down)",
    "TRUE; directional_score_sum_means = up_score + down_score_reoriented",
    "two-sided Wilcoxon rank-sum test for ACLT_t7 or ACLT_t28 vs Control; exact = FALSE",
    "Benjamini-Hochberg FDR across all 12 generated score-level comparisons",
    file.path(out_dir, "step19_current78_pig_signature_scores_by_sample.csv"),
    file.path(out_dir, "step19_current78_pig_signature_score_group_comparisons.csv"),
    file.path(out_dir, "step19_current78_pig_signature_TMM_logCPM_matrix.csv"),
    file.path(out_dir, "step19_current78_TMM_normalization_factors.csv"),
    out_dir
  ),
  stringsAsFactors = FALSE
)
write_csv(run_summary, file.path(out_dir, "step19_current78_pig_signature_score_run_summary.csv"))

version_df <- data.frame(
  item = c("R_version", "platform", "edgeR_version", "ggplot2_version", "score_input", "normalization", "logCPM_prior_count", "row_standardization"),
  value = c(
    paste(R.version$major, R.version$minor, sep = "."),
    R.version$platform,
    as.character(utils::packageVersion("edgeR")),
    ifelse(requireNamespace("ggplot2", quietly = TRUE), as.character(utils::packageVersion("ggplot2")), NA_character_),
    "Step18_current78 pig signature gene table and Step16 full gene-level count matrix",
    "edgeR TMM-normalized logCPM from full count matrix",
    "1",
    "row-wise z-score across all 18 pig early samples"
  ),
  stringsAsFactors = FALSE
)
write_csv(version_df, file.path(out_dir, "step19_current78_pig_signature_score_software_versions.csv"))
writeLines(capture.output(sessionInfo()), file.path(out_dir, "step19_current78_sessionInfo.txt"))
if (nrow(plot_files) > 0) write_csv(plot_files, file.path(out_dir, "step19_current78_plot_files.csv"))

current_script_path <- get_script_path()
script_archive_out <- file.path(out_script_dir, "step19_current78_pig_signature_score_mouse_style.R")
script_archive_project <- file.path(scripts_dir, "step19_current78_pig_signature_score_mouse_style.R")
if (!is.na(current_script_path) && file.exists(current_script_path)) {
  file.copy(current_script_path, script_archive_out, overwrite = TRUE)
  file.copy(current_script_path, script_archive_project, overwrite = TRUE)
  cat("Archived script to: ", script_archive_out, "\n", sep = "")
  cat("Archived script to: ", script_archive_project, "\n", sep = "")
} else {
  cat("Script archive skipped because commandArgs() did not expose a --file path.\n")
}

## =========================
## 9. Console summary and summary-to-send log
## =========================

cat("\n===== STEP19_CURRENT78 SUMMARY =====\n")
print(run_summary)
cat("\nSignature direction counts:\n")
print(table(sig_df[[direction_col]]))
cat("\nGroup comparison statistics:\n")
print(stats_df)
cat("\nMain score table:\n", file.path(out_dir, "step19_current78_pig_signature_scores_by_sample.csv"), "\n", sep = "")
cat("Summary to send me:\n", summary_log_file, "\n", sep = "")
cat("\nStep19 current78 pig signature score completed successfully.\n")

summary_lines <- c(
  "===== STEP19_CURRENT78 SUMMARY TO SEND =====",
  paste0("Run time: ", format(Sys.time())),
  "",
  "Main run summary:",
  paste(capture.output(print(run_summary)), collapse = "\n"),
  "",
  "Signature direction counts:",
  paste(capture.output(print(table(sig_df[[direction_col]]))), collapse = "\n"),
  "",
  "Group comparison statistics:",
  paste(capture.output(print(stats_df)), collapse = "\n"),
  "",
  "Primary output files:",
  paste0("scores_by_sample: ", file.path(out_dir, "step19_current78_pig_signature_scores_by_sample.csv")),
  paste0("scores_long: ", file.path(out_dir, "step19_current78_pig_signature_scores_long.csv")),
  paste0("group_comparisons: ", file.path(out_dir, "step19_current78_pig_signature_score_group_comparisons.csv")),
  paste0("gene_metadata: ", file.path(out_dir, "step19_current78_pig_signature_gene_metadata.csv")),
  paste0("TMM_logCPM_matrix: ", file.path(out_dir, "step19_current78_pig_signature_TMM_logCPM_matrix.csv")),
  paste0("TMM_normalization_factors: ", file.path(out_dir, "step19_current78_TMM_normalization_factors.csv")),
  paste0("zscore_matrix: ", file.path(out_dir, "step19_current78_pig_signature_zscore_matrix.csv")),
  "",
  "Plots:",
  if (nrow(plot_files) > 0) paste(capture.output(print(plot_files)), collapse = "\n") else "No plots generated because ggplot2 was unavailable.",
  "",
  "Interpretation checkpoint:",
  "Please verify that n_signature_genes_used = 75, n_up_signature_genes = 65, and n_down_signature_genes = 10.",
  "The expression input is TMM-normalized logCPM from the full Step16 count matrix, followed by row-wise z-score across the 18 samples.",
  "The primary directional_score follows the current methods formula: (sum up z + sum -down z)/(n_up+n_down).",
  "directional_score_sum_means is saved only as an audit/backward-comparison score."
)
writeLines(summary_lines, summary_log_file)

sink()
file.copy(full_log_file, full_log_project_copy, overwrite = TRUE)
file.copy(summary_log_file, summary_log_project_copy, overwrite = TRUE)
cat("\nStep19 current78 pig signature score completed.\n")
cat("Summary to send me: ", summary_log_file, "\n", sep = "")
cat("Project-level summary copy: ", summary_log_project_copy, "\n", sep = "")
