# Step06: Redraw mouse Figure 1B/1C PCA using locked-method Step05 voom logCPM matrices.
# Purpose:
# This locked-method Step06 uses the second voom logCPM matrices generated by the locked
# Step05 duplicateCorrelation limma-voom workflow. It does not create an independent PCA
# preprocessing pipeline. PCA is performed on the same filterByExpr-retained, TMM-normalized,
# second-voom expression matrix used for downstream paired DE analysis.

base_dir <- "E:/R/ACLsenescence2/rebuild_submission/02_mouse_discovery"

voom_1w_file <- file.path(base_dir, "03_DE_analysis", "step05_voom_logCPM_1W.csv")
voom_4w_file <- file.path(base_dir, "03_DE_analysis", "step05_voom_logCPM_4W.csv")
anno_1w_file <- file.path(base_dir, "01_metadata", "step04_anno_1W.csv")
anno_4w_file <- file.path(base_dir, "01_metadata", "step04_anno_4W.csv")

figure_dir <- file.path(base_dir, "06_figures", "Figure1")
table_dir <- file.path(base_dir, "07_tables", "step06_mouse_Figure1BC_PCA")
log_dir <- file.path(base_dir, "08_logs")
script_dir <- file.path(base_dir, "09_scripts")

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(log_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(script_dir, recursive = TRUE, showWarnings = FALSE)

step_name <- "step06_mouse_Figure1BC_PCA"
log_file <- file.path(log_dir, paste0(step_name, "_log.txt"))

old_files <- c(
  list.files(table_dir, full.names = TRUE, recursive = TRUE),
  file.path(figure_dir, "Figure1B_mouse_1W_PCA.png"),
  file.path(figure_dir, "Figure1B_mouse_1W_PCA.pdf"),
  file.path(figure_dir, "Figure1C_mouse_4W_PCA.png"),
  file.path(figure_dir, "Figure1C_mouse_4W_PCA.pdf"),
  log_file,
  file.path(script_dir, "step06_mouse_Figure1BC_PCA.R")
)
unlink(old_files[file.exists(old_files)], force = TRUE)

# Clean legacy PCA outputs from the previous numbering to avoid step05/step06 confusion.
legacy_step05_table_dir <- file.path(base_dir, "07_tables", "step05_mouse_Figure1BC_PCA")
legacy_step05_files <- c(
  if (dir.exists(legacy_step05_table_dir)) list.files(legacy_step05_table_dir, full.names = TRUE, recursive = TRUE) else character(0),
  file.path(log_dir, "step05_mouse_Figure1BC_PCA_log.txt"),
  file.path(script_dir, "step05_mouse_Figure1BC_PCA.R")
)
unlink(legacy_step05_files[file.exists(legacy_step05_files)], force = TRUE)

sink(log_file, split = TRUE)

cat("===== STEP06 LOCKED PCA FROM STEP05 SECOND VOOM MATRIX =====\n")
cat("Run time: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "\n", sep = "")
cat("Locked PCA input: Step05 second voom logCPM matrix after filterByExpr and TMM normalization.\n")
cat("PCA method: prcomp(t(voom_E), center = TRUE, scale. = FALSE).\n\n")

get_script_path <- function() {
  cmd_args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", cmd_args, value = TRUE)
  if (length(file_arg) > 0) return(normalizePath(sub("^--file=", "", file_arg[1]), winslash = "/", mustWork = FALSE))
  NA_character_
}

archive_current_script <- function(path) {
  src <- get_script_path()
  if (!is.na(src) && file.exists(src)) {
    writeLines(readLines(src, warn = FALSE, encoding = "UTF-8"), path, useBytes = TRUE)
    cat("Script archived to: ", path, "\n", sep = "")
  } else {
    writeLines("# Step06 archive fallback.", path, useBytes = TRUE)
    cat("Script path not detected; archive fallback saved.\n")
  }
}

safe_library <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}

write_csv <- function(x, path, row_names = FALSE) {
  write.csv(x, path, row.names = row_names, fileEncoding = "UTF-8")
  cat("Saved: ", path, "\n", sep = "")
}

standardize_sex <- function(x) {
  x <- as.character(x)
  out <- x
  out[toupper(x) == "M"] <- "Male"
  out[toupper(x) == "F"] <- "Female"
  factor(out, levels = c("Female", "Male"))
}

build_pair_lines <- function(pca_df) {
  sp <- split(pca_df, pca_df$mouse_id)
  out <- lapply(sp, function(d) {
    if (nrow(d) != 2) return(NULL)
    data.frame(mouse_id = d$mouse_id[1], x = d$PC1[1], y = d$PC2[1],
               xend = d$PC1[2], yend = d$PC2[2], stringsAsFactors = FALSE)
  })
  out <- out[!vapply(out, is.null, logical(1))]
  if (length(out) == 0) return(data.frame(mouse_id = character(), x = numeric(), y = numeric(), xend = numeric(), yend = numeric()))
  do.call(rbind, out)
}

make_pca_plot <- function(pca_df, line_df, pc1_pct, pc2_pct, title_text) {
  ggplot2::ggplot() +
    ggplot2::geom_segment(
      data = line_df,
      ggplot2::aes(x = x, y = y, xend = xend, yend = yend),
      linetype = "dashed", linewidth = 0.35, color = "grey55", alpha = 0.65
    ) +
    ggplot2::geom_point(
      data = pca_df,
      ggplot2::aes(x = PC1, y = PC2, color = treatment, shape = sex),
      size = 2.8, alpha = 0.95
    ) +
    ggrepel::geom_text_repel(
      data = pca_df,
      ggplot2::aes(x = PC1, y = PC2, label = sample_id),
      size = 3, box.padding = 0.25, point.padding = 0.15,
      min.segment.length = 0, max.overlaps = Inf, show.legend = FALSE
    ) +
    ggplot2::scale_color_manual(values = c("Contra" = "#F8766D", "ACLR" = "#00BFC4"), drop = FALSE) +
    ggplot2::scale_shape_manual(values = c("Female" = 16, "Male" = 17), drop = FALSE) +
    ggplot2::theme_bw(base_size = 11) +
    ggplot2::labs(
      title = title_text,
      x = paste0("PC1 (", sprintf("%.1f", pc1_pct), "%)"),
      y = paste0("PC2 (", sprintf("%.1f", pc2_pct), "%)"),
      color = "treatment",
      shape = "Sex"
    ) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 0.5),
      panel.grid.major = ggplot2::element_line(color = "grey90"),
      panel.grid.minor = ggplot2::element_blank()
    )
}

run_pca_one_timepoint <- function(voom_file, anno_file, timepoint, panel, title_text, out_png, out_pdf) {
  if (!file.exists(voom_file)) stop("Missing Step05 second voom matrix: ", voom_file, "\nPlease run locked-method Step05 first.")
  if (!file.exists(anno_file)) stop("Missing Step04 annotation file: ", anno_file)

  voom_E <- read.csv(voom_file, row.names = 1, stringsAsFactors = FALSE, check.names = FALSE)
  voom_E <- as.matrix(voom_E)
  storage.mode(voom_E) <- "numeric"

  anno <- read.csv(anno_file, stringsAsFactors = FALSE)
  anno$sex <- standardize_sex(anno$sex)
  anno$treatment <- factor(anno$treatment, levels = c("Contra", "ACLR"))
  anno <- anno[match(colnames(voom_E), anno$sample_id), , drop = FALSE]

  if (any(is.na(anno$sample_id))) stop(timepoint, ": annotation does not match Step05 voom matrix columns.")
  if (!all(c("Contra", "ACLR") %in% anno$treatment)) stop(timepoint, ": missing Contra or ACLR group.")
  if (length(unique(anno$mouse_id)) * 2 != nrow(anno)) stop(timepoint, ": paired mouse structure is incomplete.")

  pca <- prcomp(t(voom_E), center = TRUE, scale. = FALSE)
  var_pct <- (pca$sdev^2 / sum(pca$sdev^2)) * 100

  pca_df <- data.frame(
    panel = panel, timepoint = timepoint, sample_id = colnames(voom_E),
    mouse_id = anno$mouse_id, sex = anno$sex, treatment = anno$treatment,
    PC1 = pca$x[, 1], PC2 = pca$x[, 2], stringsAsFactors = FALSE
  )

  line_df <- build_pair_lines(pca_df)
  p <- make_pca_plot(pca_df, line_df, var_pct[1], var_pct[2], title_text)

  ggplot2::ggsave(out_png, p, width = 7.0, height = 5.5, dpi = 300)
  ggplot2::ggsave(out_pdf, p, width = 7.0, height = 5.5)

  list(
    pca_df = pca_df,
    line_df = line_df,
    variance = data.frame(panel = panel, timepoint = timepoint,
                          PC = paste0("PC", seq_along(var_pct)),
                          variance_explained_pct = as.numeric(var_pct),
                          stringsAsFactors = FALSE),
    summary = data.frame(panel = panel, timepoint = timepoint, PCA_input = voom_file,
                         genes_used = nrow(voom_E), samples = ncol(voom_E),
                         PCA_center = TRUE, PCA_scale = FALSE,
                         PC1_variance_pct = var_pct[1], PC2_variance_pct = var_pct[2],
                         pair_lines = nrow(line_df), output_png = out_png, output_pdf = out_pdf,
                         stringsAsFactors = FALSE)
  )
}

safe_library("ggplot2")
safe_library("ggrepel")
archive_current_script(file.path(script_dir, "step06_mouse_Figure1BC_PCA.R"))

res_1w <- run_pca_one_timepoint(
  voom_file = voom_1w_file, anno_file = anno_1w_file, timepoint = "1W",
  panel = "Figure1B", title_text = "GSE271903_1W PCA",
  out_png = file.path(figure_dir, "Figure1B_mouse_1W_PCA.png"),
  out_pdf = file.path(figure_dir, "Figure1B_mouse_1W_PCA.pdf")
)

res_4w <- run_pca_one_timepoint(
  voom_file = voom_4w_file, anno_file = anno_4w_file, timepoint = "4W",
  panel = "Figure1C", title_text = "GSE271903_4W PCA",
  out_png = file.path(figure_dir, "Figure1C_mouse_4W_PCA.png"),
  out_pdf = file.path(figure_dir, "Figure1C_mouse_4W_PCA.pdf")
)

write_csv(res_1w$pca_df, file.path(table_dir, "step06_Figure1B_1W_PCA_source_data.csv"))
write_csv(res_4w$pca_df, file.path(table_dir, "step06_Figure1C_4W_PCA_source_data.csv"))
write_csv(res_1w$line_df, file.path(table_dir, "step06_Figure1B_1W_pair_line_source_data.csv"))
write_csv(res_4w$line_df, file.path(table_dir, "step06_Figure1C_4W_pair_line_source_data.csv"))

variance_summary <- rbind(res_1w$variance, res_4w$variance)
write_csv(variance_summary, file.path(table_dir, "step06_PCA_variance_explained_summary.csv"))

run_summary <- rbind(res_1w$summary, res_4w$summary)
write_csv(run_summary, file.path(table_dir, "step06_PCA_run_summary.csv"))

software_versions <- data.frame(
  item = c("R", "ggplot2", "ggrepel"),
  version = c(as.character(getRversion()), as.character(utils::packageVersion("ggplot2")), as.character(utils::packageVersion("ggrepel"))),
  stringsAsFactors = FALSE
)
write_csv(software_versions, file.path(table_dir, "step06_software_versions.csv"))
writeLines(capture.output(sessionInfo()), file.path(table_dir, "step06_sessionInfo.txt"))

cat("\n===== STEP06 SUMMARY =====\n")
cat("\nLocked PCA run summary:\n")
print(run_summary)
cat("\nPC1/PC2 variance:\n")
print(variance_summary[variance_summary$PC %in% c("PC1", "PC2"), ])
cat("\nStep06 locked PCA completed successfully.\n")

sink()
