# Step06 mouse sample-level MDS QC from Step05 second voom logCPM matrices.
# This script generates within-timepoint mouse MDS QC plots for 1W and 4W only.
# Inputs are the saved Step05 paired limma-voom second voom-transformed logCPM matrices.
# Outputs are saved under supplement/S1 for manuscript-ready supplemental QC records.

options(stringsAsFactors = FALSE)

step_name <- "step06_mouse_MDS_from_step05_voom_logCPM"
project_root <- "E:/R/ACLsenescence2/rebuild_submission/02_mouse_discovery"

de_dir <- file.path(project_root, "03_DE_analysis")
metadata_dir <- file.path(project_root, "01_metadata")
supplement_dir <- file.path(project_root, "supplement")
output_root <- file.path(supplement_dir, "S1")

voom_1w_file <- file.path(de_dir, "step05_voom_logCPM_1W.csv")
voom_4w_file <- file.path(de_dir, "step05_voom_logCPM_4W.csv")

figures_dir <- file.path(output_root, "figures")
tables_dir <- file.path(output_root, "tables")
source_dir <- file.path(output_root, "source_data")
logs_dir <- file.path(output_root, "logs")
code_dir <- file.path(output_root, "code")

for (d in c(output_root, figures_dir, tables_dir, source_dir, logs_dir, code_dir)) {
  if (!dir.exists(d)) dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

# Remove only previous outputs generated by this same step, not the entire S1 folder.
cleanup_step_files <- function(dir_path, prefix) {
  if (!dir.exists(dir_path)) return(invisible(NULL))
  old_files <- list.files(dir_path, pattern = paste0("^", prefix), full.names = TRUE)
  if (length(old_files) > 0) unlink(old_files, recursive = TRUE, force = TRUE)
  invisible(NULL)
}
for (d in c(figures_dir, tables_dir, source_dir, logs_dir, code_dir)) cleanup_step_files(d, step_name)

log_file <- file.path(logs_dir, paste0(step_name, "_full_run_log.txt"))
summary_txt <- file.path(logs_dir, paste0(step_name, "_summary_to_send_me.txt"))
error_file <- file.path(logs_dir, paste0(step_name, "_error_log.txt"))
log_lines <- character(0)

add_log <- function(...) {
  msg <- paste(..., collapse = " ")
  log_lines <<- c(log_lines, msg)
  cat(msg, "\n")
  writeLines(log_lines, log_file, useBytes = TRUE)
}

write_summary_text <- function(status = "SUCCESS", extra = character(0)) {
  lines <- c(
    paste0("===== ", step_name, " summary ====="),
    paste0("Status: ", status),
    paste0("Run time: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
    paste0("Project root: ", project_root),
    paste0("Output root: ", output_root),
    "",
    log_lines,
    "",
    extra
  )
  writeLines(lines, summary_txt, useBytes = TRUE)
}

safe_write_csv <- function(x, path) {
  utils::write.csv(x, path, row.names = FALSE, fileEncoding = "UTF-8")
}

require_package <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Missing required R package: ", pkg, ". Please install it before rerunning this script.")
  }
}

normalize_sample_id <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x <- gsub("[[:space:]]+", "", x)
  x <- sub("^read_count_", "", x, ignore.case = TRUE)
  x <- sub("^X(?=[A-Za-z]*[0-9])", "", x, perl = TRUE)
  x
}

read_table_auto <- function(path) {
  ext <- tolower(tools::file_ext(path))
  if (ext == "csv") {
    utils::read.csv(path, check.names = FALSE, stringsAsFactors = FALSE)
  } else if (ext %in% c("tsv", "txt")) {
    utils::read.delim(path, check.names = FALSE, stringsAsFactors = FALSE)
  } else if (ext %in% c("xlsx", "xls")) {
    require_package("readxl")
    as.data.frame(readxl::read_excel(path, .name_repair = "minimal"), stringsAsFactors = FALSE)
  } else {
    stop("Unsupported table file extension: ", path)
  }
}

pick_column <- function(df, candidates, required = TRUE, label = "column") {
  nms <- names(df)
  hit <- match(tolower(candidates), tolower(nms))
  hit <- hit[!is.na(hit)]
  if (length(hit) > 0) return(nms[hit[1]])
  if (required) {
    stop("Could not find ", label, ". Checked: ", paste(candidates, collapse = ", "),
         ". Available columns: ", paste(nms, collapse = ", "))
  }
  NA_character_
}

find_metadata_file <- function(timepoint) {
  candidates <- c(
    file.path(metadata_dir, paste0("step04_anno_", timepoint, ".csv")),
    file.path(supplement_dir, paste0("step04_anno_", timepoint, ".csv")),
    list.files(project_root, pattern = paste0("step0?4.*anno.*", timepoint, ".*\\.csv$"), recursive = TRUE, full.names = TRUE, ignore.case = TRUE),
    list.files(project_root, pattern = paste0("anno.*", timepoint, ".*\\.csv$"), recursive = TRUE, full.names = TRUE, ignore.case = TRUE),
    list.files(project_root, pattern = paste0("metadata.*", timepoint, ".*\\.csv$"), recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
  )
  candidates <- unique(candidates[file.exists(candidates)])
  if (length(candidates) == 0) {
    stop("Could not find metadata file for ", timepoint, ". Expected step04_anno_", timepoint,
         ".csv under 01_metadata or supplement.")
  }
  candidates[1]
}

infer_group_column <- function(meta) {
  candidates <- c("treatment", "Treatment", "group", "Group", "condition", "Condition", "core_group", "plot_group")
  col <- pick_column(meta, candidates, required = FALSE, label = "treatment/group column")
  if (!is.na(col)) return(col)
  for (nm in names(meta)) {
    vals <- unique(as.character(meta[[nm]]))
    vals <- vals[!is.na(vals) & vals != ""]
    vals_low <- tolower(vals)
    if (any(grepl("aclr|contra|contralateral|control|ctrl", vals_low))) return(nm)
  }
  NA_character_
}

clean_treatment <- function(x, sample_id = NULL) {
  x0 <- as.character(x)
  x0[is.na(x0)] <- ""
  x_low <- tolower(x0)
  out <- x0
  out[grepl("aclr|acl_r|injur|rupture|surgery|case", x_low)] <- "ACLR"
  out[grepl("contra|contralateral|control|ctrl|sham|normal", x_low)] <- "Contra"
  out <- gsub("^1W[_ -]*", "", out, ignore.case = TRUE)
  out <- gsub("^4W[_ -]*", "", out, ignore.case = TRUE)

  unresolved <- !(out %in% c("ACLR", "Contra"))
  if (!is.null(sample_id) && any(unresolved)) {
    sid <- as.character(sample_id)
    # Fallback used only when metadata group labels are not explicit.
    # In this mouse dataset, sample suffixes often encode side labels used in previous QC scripts.
    out[unresolved & grepl("R$", sid, ignore.case = TRUE)] <- "ACLR"
    out[unresolved & grepl("L$", sid, ignore.case = TRUE)] <- "Contra"
  }
  out
}

read_voom_matrix <- function(path) {
  if (!file.exists(path)) stop("Missing voom logCPM matrix: ", path)
  add_log("Reading voom logCPM matrix: ", path)
  df <- utils::read.csv(path, check.names = FALSE, stringsAsFactors = FALSE)
  if (nrow(df) == 0 || ncol(df) < 3) stop("Invalid voom matrix dimensions in: ", path)

  first_col <- df[[1]]
  first_col_numeric <- suppressWarnings(as.numeric(first_col))
  first_col_is_gene <- mean(is.na(first_col_numeric)) > 0.5

  if (first_col_is_gene) {
    gene_id <- as.character(first_col)
    gene_id[is.na(gene_id) | gene_id == ""] <- paste0("gene_row_", which(is.na(gene_id) | gene_id == ""))
    mat_df <- df[, -1, drop = FALSE]
  } else {
    gene_id <- paste0("gene_row_", seq_len(nrow(df)))
    mat_df <- df
  }

  mat <- as.matrix(data.frame(lapply(mat_df, function(z) suppressWarnings(as.numeric(z))), check.names = FALSE))
  rownames(mat) <- make.unique(gene_id)
  colnames(mat) <- normalize_sample_id(colnames(mat_df))

  keep_rows <- rowSums(!is.na(mat)) == ncol(mat)
  if (sum(!keep_rows) > 0) add_log("Rows removed due to NA values: ", sum(!keep_rows))
  mat <- mat[keep_rows, , drop = FALSE]
  storage.mode(mat) <- "numeric"

  add_log("Imported matrix dimensions: ", nrow(mat), " genes x ", ncol(mat), " samples")
  mat
}

prepare_metadata <- function(path, timepoint) {
  add_log("Reading metadata for ", timepoint, ": ", path)
  meta <- read_table_auto(path)

  sample_col <- pick_column(
    meta,
    c("sample_id", "sample", "Sample", "SampleID", "sample_name", "geo_accession", "GSM", "read_count_sample", "matrix_sample"),
    required = TRUE,
    label = "metadata sample ID"
  )
  group_col <- infer_group_column(meta)
  sex_col <- pick_column(meta, c("sex", "Sex", "gender", "Gender"), required = FALSE, label = "sex column")
  mouse_col <- pick_column(meta, c("mouse_id", "Mouse ID", "Mouse_ID", "mouse", "Mouse", "animal_id", "Animal ID"), required = FALSE, label = "mouse ID column")

  out <- data.frame(
    sample_id = normalize_sample_id(meta[[sample_col]]),
    original_sample_id = as.character(meta[[sample_col]]),
    timepoint = timepoint,
    stringsAsFactors = FALSE
  )

  if (!is.na(group_col)) {
    out$treatment_raw <- as.character(meta[[group_col]])
  } else {
    out$treatment_raw <- NA_character_
  }
  out$treatment <- clean_treatment(out$treatment_raw, out$sample_id)

  if (!is.na(sex_col)) {
    out$sex <- as.character(meta[[sex_col]])
  } else {
    out$sex <- "Unknown"
  }

  if (!is.na(mouse_col)) {
    out$mouse_id <- as.character(meta[[mouse_col]])
  } else {
    # Fallback: remove final L/R side suffix from sample ID if present.
    out$mouse_id <- sub("[LR]$", "", out$sample_id, ignore.case = TRUE)
  }

  out <- out[!duplicated(out$sample_id), , drop = FALSE]
  out$treatment <- factor(out$treatment, levels = c("Contra", "ACLR", setdiff(unique(out$treatment), c("Contra", "ACLR"))))
  out$sex <- factor(out$sex)

  add_log("Metadata rows after de-duplication for ", timepoint, ": ", nrow(out))
  add_log("Treatment counts for ", timepoint, ": ", paste(names(table(out$treatment, useNA = "ifany")), as.integer(table(out$treatment, useNA = "ifany")), collapse = "; "))
  out
}

match_matrix_and_metadata <- function(mat, meta, timepoint) {
  idx <- match(meta$sample_id, colnames(mat))
  if (anyNA(idx)) {
    missing_samples <- meta$sample_id[is.na(idx)]
    stop("For ", timepoint, ", metadata samples not found in voom matrix columns: ", paste(missing_samples, collapse = ", "),
         "\nFirst matrix columns: ", paste(head(colnames(mat), 30), collapse = ", "))
  }
  mat2 <- mat[, idx, drop = FALSE]
  colnames(mat2) <- meta$sample_id
  rownames(meta) <- meta$sample_id
  if (!identical(colnames(mat2), meta$sample_id)) stop("Internal matching error for ", timepoint)
  add_log("Matched ", timepoint, ": ", ncol(mat2), " samples and ", nrow(mat2), " genes")
  list(mat = mat2, meta = meta)
}

make_mds <- function(logcpm_mat, meta, timepoint) {
  add_log("Running limma::plotMDS for ", timepoint, " using second voom logCPM matrix")
  if (ncol(logcpm_mat) < 3) stop("Too few samples for MDS: ", timepoint)
  if (nrow(logcpm_mat) < 500) add_log("WARNING: fewer than 500 genes available for MDS in ", timepoint)

  mds <- limma::plotMDS(logcpm_mat, top = 500, gene.selection = "common", plot = FALSE)
  coord <- data.frame(
    timepoint = timepoint,
    sample_id = colnames(logcpm_mat),
    MDS1 = as.numeric(mds$x),
    MDS2 = as.numeric(mds$y),
    stringsAsFactors = FALSE
  )
  coord <- merge(coord, meta, by = "sample_id", all.x = TRUE, sort = FALSE)
  coord$timepoint <- timepoint

  coord_file <- file.path(source_dir, paste0(step_name, "_", timepoint, "_MDS_coordinates.csv"))
  gene_file <- file.path(source_dir, paste0(step_name, "_", timepoint, "_input_gene_ids.csv"))
  safe_write_csv(coord, coord_file)
  safe_write_csv(data.frame(gene_id = rownames(logcpm_mat), stringsAsFactors = FALSE), gene_file)

  pair_df <- coord[!is.na(coord$mouse_id) & coord$mouse_id != "", , drop = FALSE]
  pair_counts <- table(pair_df$mouse_id)
  valid_pairs <- names(pair_counts)[pair_counts >= 2]
  pair_df <- pair_df[pair_df$mouse_id %in% valid_pairs, , drop = FALSE]
  pair_df <- pair_df[order(pair_df$mouse_id, pair_df$treatment), , drop = FALSE]

  p <- ggplot2::ggplot(coord, ggplot2::aes(x = MDS1, y = MDS2)) +
    ggplot2::theme_bw(base_size = 12) +
    ggplot2::labs(
      title = paste0("Mouse ", timepoint, " sample-level MDS QC"),
      subtitle = "Input: Step05 paired limma-voom second voom-transformed logCPM matrix",
      x = "MDS dimension 1",
      y = "MDS dimension 2",
      color = "Treatment",
      shape = "Sex"
    ) +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold"),
      legend.position = "right"
    )

  if (nrow(pair_df) > 0) {
    p <- p + ggplot2::geom_line(
      data = pair_df,
      ggplot2::aes(group = mouse_id),
      linewidth = 0.35,
      linetype = "dashed",
      alpha = 0.55,
      color = "grey45"
    )
  }

  p <- p + ggplot2::geom_point(ggplot2::aes(color = treatment, shape = sex), size = 3.0, alpha = 0.95)

  if (requireNamespace("ggrepel", quietly = TRUE)) {
    p <- p + ggrepel::geom_text_repel(
      ggplot2::aes(label = sample_id, color = treatment),
      size = 2.7,
      max.overlaps = Inf,
      show.legend = FALSE,
      box.padding = 0.25,
      point.padding = 0.2,
      min.segment.length = 0
    )
  } else {
    p <- p + ggplot2::geom_text(ggplot2::aes(label = sample_id, color = treatment), size = 2.5, vjust = -0.8, show.legend = FALSE)
  }

  pdf_file <- file.path(figures_dir, paste0(step_name, "_", timepoint, "_MDS.pdf"))
  png_file <- file.path(figures_dir, paste0(step_name, "_", timepoint, "_MDS.png"))
  ggplot2::ggsave(pdf_file, p, width = 7.2, height = 5.6)
  ggplot2::ggsave(png_file, p, width = 7.2, height = 5.6, dpi = 600)

  summary_row <- data.frame(
    step_name = step_name,
    timepoint = timepoint,
    input_matrix = "Step05 paired limma-voom second voom-transformed logCPM",
    mds_function = "limma::plotMDS",
    top = 500,
    gene_selection = "common",
    n_genes_input = nrow(logcpm_mat),
    n_samples_input = ncol(logcpm_mat),
    n_contra = sum(coord$treatment == "Contra", na.rm = TRUE),
    n_aclr = sum(coord$treatment == "ACLR", na.rm = TRUE),
    n_pair_lines_drawn = length(unique(pair_df$mouse_id)),
    coordinate_file = coord_file,
    input_gene_file = gene_file,
    pdf_file = pdf_file,
    png_file = png_file,
    stringsAsFactors = FALSE
  )

  add_log("Saved ", timepoint, " MDS PDF: ", pdf_file)
  add_log("Saved ", timepoint, " MDS PNG: ", png_file)
  add_log("Saved ", timepoint, " MDS coordinates: ", coord_file)

  list(coord = coord, plot = p, summary = summary_row)
}

run_main <- function() {
  require_package("limma")
  require_package("ggplot2")

  add_log("Starting ", step_name)
  add_log("1W voom file: ", voom_1w_file)
  add_log("4W voom file: ", voom_4w_file)
  add_log("Output root: ", output_root)

  if (!file.exists(voom_1w_file)) stop("1W voom logCPM file does not exist: ", voom_1w_file)
  if (!file.exists(voom_4w_file)) stop("4W voom logCPM file does not exist: ", voom_4w_file)

  meta_1w_file <- find_metadata_file("1W")
  meta_4w_file <- find_metadata_file("4W")
  add_log("1W metadata file: ", meta_1w_file)
  add_log("4W metadata file: ", meta_4w_file)

  mat_1w <- read_voom_matrix(voom_1w_file)
  mat_4w <- read_voom_matrix(voom_4w_file)
  meta_1w <- prepare_metadata(meta_1w_file, "1W")
  meta_4w <- prepare_metadata(meta_4w_file, "4W")

  matched_1w <- match_matrix_and_metadata(mat_1w, meta_1w, "1W")
  matched_4w <- match_matrix_and_metadata(mat_4w, meta_4w, "4W")

  safe_write_csv(matched_1w$meta, file.path(tables_dir, paste0(step_name, "_1W_matched_metadata.csv")))
  safe_write_csv(matched_4w$meta, file.path(tables_dir, paste0(step_name, "_4W_matched_metadata.csv")))

  res_1w <- make_mds(matched_1w$mat, matched_1w$meta, "1W")
  res_4w <- make_mds(matched_4w$mat, matched_4w$meta, "4W")

  summary_df <- rbind(res_1w$summary, res_4w$summary)
  summary_csv <- file.path(tables_dir, paste0(step_name, "_summary.csv"))
  safe_write_csv(summary_df, summary_csv)

  coord_all <- rbind(res_1w$coord, res_4w$coord)
  coord_all_file <- file.path(source_dir, paste0(step_name, "_all_MDS_coordinates.csv"))
  safe_write_csv(coord_all, coord_all_file)

  input_record <- data.frame(
    input_name = c("voom_1W_file", "voom_4W_file", "metadata_1W_file", "metadata_4W_file"),
    path = c(voom_1w_file, voom_4w_file, meta_1w_file, meta_4w_file),
    md5 = as.character(tools::md5sum(c(voom_1w_file, voom_4w_file, meta_1w_file, meta_4w_file))),
    stringsAsFactors = FALSE
  )
  input_record_file <- file.path(logs_dir, paste0(step_name, "_input_file_record.csv"))
  safe_write_csv(input_record, input_record_file)

  version_df <- data.frame(
    item = c("R", "limma", "ggplot2", "ggrepel"),
    version = c(
      paste(R.version$major, R.version$minor, sep = "."),
      as.character(utils::packageVersion("limma")),
      as.character(utils::packageVersion("ggplot2")),
      if (requireNamespace("ggrepel", quietly = TRUE)) as.character(utils::packageVersion("ggrepel")) else "not installed"
    ),
    stringsAsFactors = FALSE
  )
  version_file <- file.path(logs_dir, paste0(step_name, "_software_versions.csv"))
  safe_write_csv(version_df, version_file)

  # Archive this exact script into S1/code when run via Rscript or sourced in RStudio.
  script_path <- tryCatch(normalizePath(sys.frames()[[1]]$ofile, winslash = "/", mustWork = FALSE), error = function(e) NA_character_)
  if (!is.na(script_path) && file.exists(script_path)) {
    file.copy(script_path, file.path(code_dir, paste0(step_name, ".R")), overwrite = TRUE)
  } else {
    cmd_args <- commandArgs(trailingOnly = FALSE)
    file_arg <- grep("^--file=", cmd_args, value = TRUE)
    if (length(file_arg) > 0) {
      script_path <- normalizePath(sub("^--file=", "", file_arg[1]), winslash = "/", mustWork = FALSE)
      if (file.exists(script_path)) file.copy(script_path, file.path(code_dir, paste0(step_name, ".R")), overwrite = TRUE)
    }
  }

  extra <- c(
    "Key output files:",
    paste0("Summary CSV: ", summary_csv),
    paste0("Combined coordinate source data: ", coord_all_file),
    paste0("Input file record: ", input_record_file),
    paste0("Software versions: ", version_file),
    "",
    "Summary table preview:",
    paste(capture.output(print(summary_df)), collapse = "\n")
  )
  write_summary_text("SUCCESS", extra)

  add_log("DONE. Summary CSV: ", summary_csv)
  add_log("DONE. Summary text to send me: ", summary_txt)
  invisible(summary_df)
}

tryCatch(
  {
    run_main()
  },
  error = function(e) {
    msg <- paste0("ERROR: ", conditionMessage(e))
    cat(msg, "\n")
    writeLines(c(msg, "", log_lines), error_file, useBytes = TRUE)
    write_summary_text("FAILED", c(msg, paste0("Error log: ", error_file)))
    stop(e)
  }
)
