# StepPCA_MDS_02_unified_limma_MDS.R
# English note: This script performs sample-level PCA and MDS for the early pig synovium dataset using the gene-level raw count matrix. Lowly expressed genes are filtered with edgeR::filterByExpr, TMM normalization is performed with edgeR::calcNormFactors, PCA is performed on filtered TMM-normalized logCPM values, and MDS is performed on the same filtered TMM-normalized logCPM matrix using limma::plotMDS for consistency with the mouse discovery dataset. All outputs, source data, figures, logs, method parameters, and reproducibility information are saved to a manuscript-ready supplementary folder.

rm(list = ls())

step_name <- "StepPCA_MDS_02_pig_early_unified_limma_MDS"
fix_version <- "2026-05-10_unified_with_mouse_limma_plotMDS_on_filtered_TMM_logCPM"

input_count_file <- "E:/R/ACLsenescence2/rebuild_submission/02_pig_early/tables/step16_pig_early_gene_count_matrix.csv"
output_root <- "E:/R/ACLsenescence2/rebuild_submission/supplementary files/MDS_PCA"

# If TRUE, only previous outputs generated by this StepPCA_MDS_02 prefix are removed from this output folder.
# This avoids mixing the earlier edgeR::plotMDS version with the unified limma::plotMDS version.
clean_previous_step_outputs <- TRUE

subdirs <- c(
  figures = file.path(output_root, "figures"),
  source_data = file.path(output_root, "source_data"),
  tables = file.path(output_root, "tables"),
  objects = file.path(output_root, "objects"),
  logs = file.path(output_root, "logs"),
  scripts = file.path(output_root, "scripts")
)
for (d in c(output_root, subdirs)) {
  if (!dir.exists(d)) dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

log_file <- file.path(subdirs["logs"], "StepPCA_MDS_02_pig_early_unified_limma_MDS_summary_log.txt")
if (file.exists(log_file)) file.remove(log_file)

sink(log_file, split = TRUE)
on.exit({
  cat("\n============================================================\n")
  cat(step_name, "finished at:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")
  cat("Summary log saved to:\n", log_file, "\n", sep = "")
  cat("============================================================\n")
  sink()
}, add = TRUE)

cat("============================================================\n")
cat(step_name, "\n")
cat("Started at:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")
cat("Fix/method version:", fix_version, "\n")
cat("============================================================\n\n")

if (clean_previous_step_outputs) {
  cat("Cleaning previous StepPCA_MDS_02 outputs from output_root subfolders...\n")
  clean_patterns <- c("^StepPCA_MDS_02_.*", "^stepPCA_MDS_02_.*", "^StepPCA_MDS_02.*")
  cleaned_files <- character(0)
  for (d in subdirs) {
    if (dir.exists(d)) {
      files <- list.files(d, full.names = TRUE)
      if (length(files) > 0) {
        base <- basename(files)
        idx <- Reduce(`|`, lapply(clean_patterns, function(p) grepl(p, base)))
        targets <- files[idx]
        # Keep the current log connection target until the end, if present.
        targets <- setdiff(normalizePath(targets, winslash = "/", mustWork = FALSE),
                           normalizePath(log_file, winslash = "/", mustWork = FALSE))
        if (length(targets) > 0) {
          ok <- file.remove(targets)
          cleaned_files <- c(cleaned_files, targets[ok])
        }
      }
    }
  }
  cat("Number of previous StepPCA_MDS_02 files removed:", length(cleaned_files), "\n")
  if (length(cleaned_files) > 0) {
    cat("Removed files:\n")
    cat(paste(cleaned_files, collapse = "\n"), "\n", sep = "")
  }
  cat("\n")
}

# Archive the running script when possible.
cmd_args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", cmd_args, value = TRUE)
if (length(file_arg) > 0) {
  running_script <- sub("^--file=", "", file_arg[1])
  if (file.exists(running_script)) {
    archived_script <- file.path(subdirs["scripts"], "StepPCA_MDS_02_pig_early_unified_limma_MDS.R")
    file.copy(running_script, archived_script, overwrite = TRUE)
    cat("Script archived to:\n", archived_script, "\n\n", sep = "")
  } else {
    cat("--file argument detected but script path does not exist; script was not archived.\n\n")
  }
} else {
  cat("Script archive note: --file argument was not detected. If running interactively, manually save this script in:\n")
  cat(subdirs["scripts"], "\n\n")
}

required_pkgs <- c("edgeR", "limma", "ggplot2")
missing_pkgs <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_pkgs) > 0) {
  stop("Missing required packages: ", paste(missing_pkgs, collapse = ", "))
}

suppressPackageStartupMessages({
  library(edgeR)
  library(limma)
  library(ggplot2)
})

ggrepel_available <- requireNamespace("ggrepel", quietly = TRUE)
if (ggrepel_available) suppressPackageStartupMessages(library(ggrepel))

cat("Required packages loaded.\n")
cat("edgeR version:", as.character(packageVersion("edgeR")), "\n")
cat("limma version:", as.character(packageVersion("limma")), "\n")
cat("ggplot2 version:", as.character(packageVersion("ggplot2")), "\n")
cat("ggrepel available for label plots:", ggrepel_available, "\n\n")

cat("Input count file:\n", input_count_file, "\n\n", sep = "")
if (!file.exists(input_count_file)) stop("Input count file does not exist: ", input_count_file)

count_df <- read.csv(input_count_file, check.names = FALSE, stringsAsFactors = FALSE)
cat("Raw count table dimension:", nrow(count_df), "rows x", ncol(count_df), "columns\n")
cat("First 10 column names:\n")
print(head(colnames(count_df), 10))
cat("\n")

if (!"gene_id" %in% colnames(count_df)) {
  stop("Expected a column named 'gene_id' in the count matrix.")
}
if (anyDuplicated(count_df$gene_id)) {
  dup_n <- sum(duplicated(count_df$gene_id))
  stop("Duplicate gene_id values detected (n duplicated rows = ", dup_n, "). Please inspect the count matrix before PCA/MDS.")
}
if (any(is.na(count_df$gene_id) | count_df$gene_id == "")) {
  stop("Missing or empty gene_id values detected.")
}

sample_cols <- setdiff(colnames(count_df), "gene_id")
expected_patterns <- grepl("^(CON|INJS|INJL)[0-9]+$", sample_cols)
if (!all(expected_patterns)) {
  stop("Unexpected sample column names detected: ", paste(sample_cols[!expected_patterns], collapse = ", "))
}

count_mat <- as.matrix(count_df[, sample_cols, drop = FALSE])
rownames(count_mat) <- count_df$gene_id
storage.mode(count_mat) <- "numeric"

if (anyNA(count_mat)) stop("NA values detected in count matrix after numeric conversion.")
if (any(count_mat < 0)) stop("Negative counts detected; raw count matrix is expected.")

cat("Validated count matrix dimension:", nrow(count_mat), "genes x", ncol(count_mat), "samples\n\n")

infer_group <- function(x) {
  if (grepl("^CON", x)) return("Control")
  if (grepl("^INJS", x)) return("ACLT_1W")
  if (grepl("^INJL", x)) return("ACLT_4W")
  return(NA_character_)
}
infer_time <- function(x) {
  if (grepl("^CON", x)) return("t0")
  if (grepl("^INJS", x)) return("t7")
  if (grepl("^INJL", x)) return("t28")
  return(NA_character_)
}
infer_number <- function(x) as.integer(sub("^[A-Z]+", "", x))

sample_metadata <- data.frame(
  sample_id = sample_cols,
  group = vapply(sample_cols, infer_group, character(1)),
  time_point = vapply(sample_cols, infer_time, character(1)),
  sample_number = vapply(sample_cols, infer_number, integer(1)),
  count_column = sample_cols,
  stringsAsFactors = FALSE
)
sample_metadata$group <- factor(sample_metadata$group, levels = c("Control", "ACLT_1W", "ACLT_4W"))
sample_metadata$time_point <- factor(sample_metadata$time_point, levels = c("t0", "t7", "t28"))

if (anyNA(sample_metadata$group)) stop("Failed to infer group for one or more samples.")
if (any(table(sample_metadata$group) != 6)) {
  cat("WARNING: expected 6 samples per group, but observed:\n")
  print(table(sample_metadata$group))
}

cat("Inferred sample metadata:\n")
print(sample_metadata)
cat("\nGroup counts:\n")
print(table(sample_metadata$group))
cat("\n")

write.csv(sample_metadata,
          file.path(subdirs["source_data"], "StepPCA_MDS_02_sample_metadata_inferred.csv"),
          row.names = FALSE)

# edgeR filtering and TMM normalization, consistent with the DE-analysis preprocessing logic.
dge <- DGEList(counts = count_mat, group = sample_metadata$group)
keep <- filterByExpr(dge, group = sample_metadata$group)
dge_filtered <- dge[keep, , keep.lib.sizes = FALSE]
dge_filtered <- calcNormFactors(dge_filtered, method = "TMM")

logcpm <- cpm(dge_filtered, log = TRUE, prior.count = 1, normalized.lib.sizes = TRUE)

filter_summary <- data.frame(
  metric = c(
    "method_version",
    "genes_before_filterByExpr",
    "genes_after_filterByExpr",
    "genes_removed_by_filterByExpr",
    "samples",
    "normalization_method",
    "logCPM_prior_count",
    "PCA_method",
    "MDS_method",
    "MDS_input",
    "MDS_top_genes",
    "MDS_gene_selection"
  ),
  value = c(
    fix_version,
    nrow(count_mat),
    nrow(dge_filtered$counts),
    nrow(count_mat) - nrow(dge_filtered$counts),
    ncol(count_mat),
    "edgeR_TMM",
    1,
    "prcomp(t(filtered_TMM_logCPM), center=TRUE, scale.=FALSE)",
    "limma::plotMDS(filtered_TMM_logCPM, top=500, gene.selection='common')",
    "filtered TMM-normalized logCPM matrix",
    500,
    "common"
  ),
  stringsAsFactors = FALSE
)
cat("Filtering and normalization summary:\n")
print(filter_summary)
cat("\n")
write.csv(filter_summary,
          file.path(subdirs["tables"], "StepPCA_MDS_02_filter_normalization_method_summary.csv"),
          row.names = FALSE)

library_summary <- data.frame(
  sample_id = colnames(count_mat),
  group = as.character(sample_metadata$group),
  raw_library_size = colSums(count_mat),
  filtered_library_size = colSums(dge_filtered$counts),
  norm_factor_TMM = dge_filtered$samples$norm.factors,
  effective_library_size = dge_filtered$samples$lib.size * dge_filtered$samples$norm.factors,
  stringsAsFactors = FALSE
)
cat("Library summary after TMM:\n")
print(library_summary)
cat("\n")
write.csv(library_summary,
          file.path(subdirs["tables"], "StepPCA_MDS_02_library_summary_after_TMM.csv"),
          row.names = FALSE)

write.csv(data.frame(gene_id = rownames(logcpm), logcpm, check.names = FALSE),
          file.path(subdirs["source_data"], "StepPCA_MDS_02_filtered_TMM_logCPM_matrix.csv"),
          row.names = FALSE)

# PCA on filtered TMM-normalized logCPM values.
pca_obj <- prcomp(t(logcpm), center = TRUE, scale. = FALSE)
pca_var <- (pca_obj$sdev^2) / sum(pca_obj$sdev^2)
pca_var_df <- data.frame(
  PC = paste0("PC", seq_along(pca_var)),
  variance_fraction = pca_var,
  variance_percent = pca_var * 100,
  stringsAsFactors = FALSE
)
cat("PCA variance explained by first five PCs:\n")
print(head(pca_var_df, 5))
cat("\n")
write.csv(pca_var_df,
          file.path(subdirs["tables"], "StepPCA_MDS_02_PCA_variance_explained.csv"),
          row.names = FALSE)

pca_coord <- data.frame(
  sample_id = rownames(pca_obj$x),
  PC1 = pca_obj$x[, 1],
  PC2 = pca_obj$x[, 2],
  PC3 = if (ncol(pca_obj$x) >= 3) pca_obj$x[, 3] else NA_real_,
  PC4 = if (ncol(pca_obj$x) >= 4) pca_obj$x[, 4] else NA_real_,
  stringsAsFactors = FALSE
)
pca_coord <- merge(pca_coord, sample_metadata, by = "sample_id", sort = FALSE)
pca_coord <- pca_coord[match(sample_metadata$sample_id, pca_coord$sample_id), ]
write.csv(pca_coord,
          file.path(subdirs["source_data"], "StepPCA_MDS_02_PCA_coordinates.csv"),
          row.names = FALSE)

# Unified MDS: use limma::plotMDS on the filtered TMM-normalized logCPM matrix.
mds_obj <- limma::plotMDS(logcpm, top = 500, gene.selection = "common", plot = FALSE)
cat("MDS object diagnostic:\n")
cat("MDS function used: limma::plotMDS\n")
cat("MDS input object: filtered TMM-normalized logCPM matrix\n")
cat("length(mds_obj$x):", length(mds_obj$x), "\n")
cat("length(mds_obj$y):", length(mds_obj$y), "\n")
cat("length(colnames(logcpm)):", length(colnames(logcpm)), "\n")
if (length(mds_obj$x) != ncol(logcpm) || length(mds_obj$y) != ncol(logcpm)) {
  stop("MDS coordinate length does not match sample number.")
}
cat("MDS sample ID source used: colnames(logcpm)\n\n")

mds_coord <- data.frame(
  sample_id = colnames(logcpm),
  MDS1 = as.numeric(mds_obj$x),
  MDS2 = as.numeric(mds_obj$y),
  stringsAsFactors = FALSE
)
mds_coord <- merge(mds_coord, sample_metadata, by = "sample_id", sort = FALSE)
mds_coord <- mds_coord[match(sample_metadata$sample_id, mds_coord$sample_id), ]
cat("MDS coordinate table preview:\n")
print(mds_coord)
cat("\n")
write.csv(mds_coord,
          file.path(subdirs["source_data"], "StepPCA_MDS_02_MDS_coordinates.csv"),
          row.names = FALSE)

saveRDS(list(
  input_count_file = input_count_file,
  method_version = fix_version,
  sample_metadata = sample_metadata,
  dge_filtered = dge_filtered,
  logcpm = logcpm,
  pca_obj = pca_obj,
  mds_obj = mds_obj,
  pca_coord = pca_coord,
  mds_coord = mds_coord,
  filter_summary = filter_summary,
  library_summary = library_summary,
  session_info = sessionInfo()
), file.path(subdirs["objects"], "StepPCA_MDS_02_pig_early_unified_limma_MDS_objects.rds"))

shape_values <- c("Control" = 16, "ACLT_1W" = 17, "ACLT_4W" = 15)

base_theme <- theme_classic(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 15),
    plot.subtitle = element_text(size = 11),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 10)
  )

pca_x_lab <- sprintf("PC1 (%.1f%%)", pca_var_df$variance_percent[1])
pca_y_lab <- sprintf("PC2 (%.1f%%)", pca_var_df$variance_percent[2])

p_pca <- ggplot(pca_coord, aes(x = PC1, y = PC2, shape = group)) +
  geom_point(size = 3.2, color = "black") +
  scale_shape_manual(values = shape_values, drop = FALSE) +
  labs(
    title = "Early pig synovium PCA",
    subtitle = "Filtered TMM-normalized logCPM matrix",
    x = pca_x_lab,
    y = pca_y_lab,
    shape = "Group"
  ) +
  scale_x_continuous(expand = expansion(mult = 0.14)) +
  scale_y_continuous(expand = expansion(mult = 0.14)) +
  coord_cartesian(clip = "off") +
  base_theme

p_pca_label <- p_pca
if (ggrepel_available) {
  p_pca_label <- p_pca_label + ggrepel::geom_text_repel(aes(label = sample_id), size = 3.6, color = "black", max.overlaps = Inf, min.segment.length = 0)
} else {
  p_pca_label <- p_pca_label + geom_text(aes(label = sample_id), size = 3.4, vjust = -0.7, color = "black")
}

p_mds <- ggplot(mds_coord, aes(x = MDS1, y = MDS2, shape = group)) +
  geom_point(size = 3.2, color = "black") +
  scale_shape_manual(values = shape_values, drop = FALSE) +
  labs(
    title = "Early pig synovium MDS",
    subtitle = "limma::plotMDS on filtered TMM-normalized logCPM; top 500 genes; common gene selection",
    x = "MDS dimension 1",
    y = "MDS dimension 2",
    shape = "Group"
  ) +
  scale_x_continuous(expand = expansion(mult = 0.16)) +
  scale_y_continuous(expand = expansion(mult = 0.16)) +
  coord_cartesian(clip = "off") +
  base_theme

p_mds_label <- p_mds
if (ggrepel_available) {
  p_mds_label <- p_mds_label + ggrepel::geom_text_repel(aes(label = sample_id), size = 3.6, color = "black", max.overlaps = Inf, min.segment.length = 0)
} else {
  p_mds_label <- p_mds_label + geom_text(aes(label = sample_id), size = 3.4, vjust = -0.7, color = "black")
}

save_plot <- function(plot_obj, pdf_file, png_file, width = 7.2, height = 5.4) {
  ggsave(pdf_file, plot_obj, width = width, height = height, units = "in", device = cairo_pdf)
  ggsave(png_file, plot_obj, width = width, height = height, units = "in", dpi = 600)
}

save_plot(p_pca,
          file.path(subdirs["figures"], "StepPCA_MDS_02_PCA_unlabeled.pdf"),
          file.path(subdirs["figures"], "StepPCA_MDS_02_PCA_unlabeled.png"))
save_plot(p_pca_label,
          file.path(subdirs["figures"], "StepPCA_MDS_02_PCA_labeled.pdf"),
          file.path(subdirs["figures"], "StepPCA_MDS_02_PCA_labeled.png"))
save_plot(p_mds,
          file.path(subdirs["figures"], "StepPCA_MDS_02_MDS_unlabeled.pdf"),
          file.path(subdirs["figures"], "StepPCA_MDS_02_MDS_unlabeled.png"))
save_plot(p_mds_label,
          file.path(subdirs["figures"], "StepPCA_MDS_02_MDS_labeled.pdf"),
          file.path(subdirs["figures"], "StepPCA_MDS_02_MDS_labeled.png"))

method_parameters <- data.frame(
  parameter = c(
    "analysis_step",
    "input_count_matrix",
    "included_samples",
    "included_groups",
    "low_expression_filter",
    "normalization",
    "logCPM_transformation",
    "PCA_function",
    "PCA_input",
    "MDS_function",
    "MDS_input",
    "MDS_top_genes",
    "MDS_gene_selection",
    "reason_for_MDS_function_choice",
    "output_root"
  ),
  value = c(
    step_name,
    input_count_file,
    "18 core early pig synovium samples",
    "Control (n=6), ACLT_1W/t7 (n=6), ACLT_4W/t28 (n=6)",
    "edgeR::filterByExpr(group = group)",
    "edgeR::calcNormFactors(method = 'TMM')",
    "edgeR::cpm(log = TRUE, prior.count = 1, normalized.lib.sizes = TRUE)",
    "stats::prcomp(center = TRUE, scale. = FALSE)",
    "transposed filtered TMM-normalized logCPM matrix",
    "limma::plotMDS",
    "filtered TMM-normalized logCPM matrix",
    "500",
    "common",
    "Unified with mouse discovery dataset MDS method: limma::plotMDS on filtered TMM-normalized logCPM values",
    output_root
  ),
  stringsAsFactors = FALSE
)
write.csv(method_parameters,
          file.path(subdirs["tables"], "StepPCA_MDS_02_method_parameters.csv"),
          row.names = FALSE)

methods_text <- c(
  "For the early pig validation dataset, exploratory sample-level PCA and MDS analyses were performed using the 18 core synovium samples, including six Control, six ACLT untreated 1-week, and six ACLT untreated 4-week samples.",
  "Raw gene-level counts were filtered using edgeR::filterByExpr, followed by TMM normalization using edgeR::calcNormFactors.",
  "PCA was performed on the filtered TMM-normalized logCPM matrix using stats::prcomp with centering and without scaling.",
  "For consistency with the mouse discovery dataset, MDS coordinates were generated from the same filtered TMM-normalized logCPM matrix using limma::plotMDS with the top 500 genes and common gene selection."
)
writeLines(methods_text,
           con = file.path(subdirs["tables"], "StepPCA_MDS_02_methods_text_unified_with_mouse.txt"))

final_summary <- data.frame(
  metric = c(
    "run_status",
    "method_version",
    "input_count_file",
    "output_root",
    "genes_before_filterByExpr",
    "genes_after_filterByExpr",
    "samples",
    "groups",
    "PCA_PC1_percent",
    "PCA_PC2_percent",
    "MDS_function",
    "MDS_input",
    "MDS1_min",
    "MDS1_max",
    "MDS2_min",
    "MDS2_max"
  ),
  value = c(
    "SUCCESS",
    fix_version,
    input_count_file,
    output_root,
    nrow(count_mat),
    nrow(dge_filtered$counts),
    ncol(count_mat),
    paste(paste(names(table(sample_metadata$group)), as.integer(table(sample_metadata$group))), collapse = "; "),
    sprintf("%.6f", pca_var_df$variance_percent[1]),
    sprintf("%.6f", pca_var_df$variance_percent[2]),
    "limma::plotMDS",
    "filtered TMM-normalized logCPM matrix",
    sprintf("%.6f", min(mds_coord$MDS1)),
    sprintf("%.6f", max(mds_coord$MDS1)),
    sprintf("%.6f", min(mds_coord$MDS2)),
    sprintf("%.6f", max(mds_coord$MDS2))
  ),
  stringsAsFactors = FALSE
)
cat("Final summary for review:\n")
print(final_summary)
cat("\n")
write.csv(final_summary,
          file.path(subdirs["tables"], "StepPCA_MDS_02_final_summary_for_review.csv"),
          row.names = FALSE)

cat("Key output files:\n")
cat("1) PCA coordinates:\n", file.path(subdirs["source_data"], "StepPCA_MDS_02_PCA_coordinates.csv"), "\n", sep = "")
cat("2) MDS coordinates:\n", file.path(subdirs["source_data"], "StepPCA_MDS_02_MDS_coordinates.csv"), "\n", sep = "")
cat("3) Filtered TMM logCPM matrix:\n", file.path(subdirs["source_data"], "StepPCA_MDS_02_filtered_TMM_logCPM_matrix.csv"), "\n", sep = "")
cat("4) Method parameters:\n", file.path(subdirs["tables"], "StepPCA_MDS_02_method_parameters.csv"), "\n", sep = "")
cat("5) Methods text:\n", file.path(subdirs["tables"], "StepPCA_MDS_02_methods_text_unified_with_mouse.txt"), "\n", sep = "")
cat("6) PCA figures:\n")
cat(file.path(subdirs["figures"], "StepPCA_MDS_02_PCA_unlabeled.pdf"), "\n", sep = "")
cat(file.path(subdirs["figures"], "StepPCA_MDS_02_PCA_labeled.pdf"), "\n", sep = "")
cat("7) MDS figures:\n")
cat(file.path(subdirs["figures"], "StepPCA_MDS_02_MDS_unlabeled.pdf"), "\n", sep = "")
cat(file.path(subdirs["figures"], "StepPCA_MDS_02_MDS_labeled.pdf"), "\n\n", sep = "")

cat("Session information:\n")
print(sessionInfo())

cat("\n============================================================\n")
cat(step_name, "completed successfully.\n")
cat("Finished at:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")
cat("============================================================\n")
