# StepH2w9_current78: pig early fastp sensitivity - GSEA stability
# Purpose:
# Compare Hallmark GSEA results between the untrimmed main pig early branch and the
# fastp-trimmed sensitivity branch using the same GSEA口径 as the current mouse/pig early analyses.
#
# Current unified GSEA口径:
#   - full Sus scrofa MSigDB Hallmark collection from msigdbr
#   - rank statistic = sign(logFC) * -log10(PValue)
#   - gene symbols are used for ranking and Hallmark membership
#   - duplicate symbols are resolved by keeping the largest absolute rank statistic
#   - fgsea parameters: minSize = 10, maxSize = 500, eps = 0, nproc = 1
#   - target pathways are extracted after full Hallmark-level analysis
#
# This script does NOT auto-archive or overwrite any manually saved R script.
# Locked update: trimmed DE inputs are fixed to exact StepH2w6 output filenames; no recursive/scored file discovery is used.

options(stringsAsFactors = FALSE)

## =========================
## 0. Paths and packages
## =========================

project_root <- "E:/R/ACLsenescence2"
rebuild_root <- file.path(project_root, "rebuild_submission")

main_pig_dir <- file.path(rebuild_root, "02_pig_early")
fastp_dir <- file.path(rebuild_root, "02_pig_early_fastp_sensitivity")

main_tables_dir <- file.path(main_pig_dir, "tables")
fastp_tables_dir <- file.path(fastp_dir, "tables")

out_dir <- file.path(fastp_tables_dir, "stepH2w9_current78_GSEA_stability")
log_dir <- file.path(out_dir, "logs")
fig_dir <- file.path(out_dir, "figures")
obj_dir <- file.path(out_dir, "objects")

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(log_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(obj_dir, recursive = TRUE, showWarnings = FALSE)

full_log_file <- file.path(log_dir, "stepH2w9_current78_GSEA_stability_full_log.txt")
summary_log_file <- file.path(log_dir, "stepH2w9_current78_GSEA_stability_summary_to_send_me.txt")

required_pkgs <- c("fgsea", "msigdbr", "ggplot2", "dplyr")
for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Required package is not installed: ", pkg, call. = FALSE)
  }
}

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
})

sink(full_log_file, split = TRUE)

cat("===== StepH2w9_current78 GSEA stability =====\n")
cat("Run time: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "\n", sep = "")
cat("Method: full Sus scrofa Hallmark fgsea; minSize=10, maxSize=500, eps=0; target pathways extracted afterward.\n\n")

# Remove stale candidate lists generated by older auto-search versions, if present.
old_candidate_files <- Sys.glob(file.path(out_dir, "stepH2w9_current78_trimmed_DE_candidates_*.csv"))
if (length(old_candidate_files) > 0) {
  unlink(old_candidate_files, force = TRUE)
  cat("Removed old auto-search candidate file(s): ", length(old_candidate_files), "\n", sep = "")
}
cat("Locked input mode: exact DE paths only; no recursive DE file search.\n\n")

## =========================
## 1. Helper functions
## =========================

stop_if_missing <- function(file, label) {
  if (!file.exists(file)) stop("Missing ", label, ": ", file, call. = FALSE)
}

safe_read_csv <- function(file) {
  read.csv(file, stringsAsFactors = FALSE, check.names = FALSE, fileEncoding = "UTF-8-BOM")
}

write_csv <- function(x, file) {
  write.csv(x, file, row.names = FALSE, fileEncoding = "UTF-8")
  cat("Saved: ", file, "\n", sep = "")
}

clean_symbol <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null", "None", "none")] <- NA_character_
  x
}

find_col <- function(df, candidates, required = TRUE, label = "column") {
  hit <- candidates[candidates %in% colnames(df)]
  if (length(hit) > 0) return(hit[1])
  if (required) {
    stop("Could not find ", label, ". Checked: ", paste(candidates, collapse = ", "),
         "\nAvailable columns: ", paste(colnames(df), collapse = ", "), call. = FALSE)
  }
  NA_character_
}

safe_p <- function(p) {
  p <- suppressWarnings(as.numeric(p))
  p[is.na(p)] <- NA_real_
  p[p <= 0] <- .Machine$double.xmin
  p
}

build_symbol_map_from_de_files <- function(files) {
  map_list <- list()
  for (f in files) {
    if (!file.exists(f)) next
    df <- safe_read_csv(f)
    gene_id_col <- find_col(df, c("gene_id", "pig_ensg", "GeneID", "Geneid", "feature_id", "ensembl_gene_id"), FALSE, "gene id column for symbol map")
    symbol_col <- find_col(df, c("gene_name", "gene_symbol", "SYMBOL", "symbol", "pig_symbol", "external_gene_name"), FALSE, "symbol column for symbol map")
    if (is.na(gene_id_col) || is.na(symbol_col)) next
    tmp <- data.frame(
      gene_id = clean_symbol(df[[gene_id_col]]),
      gene_symbol = clean_symbol(df[[symbol_col]]),
      stringsAsFactors = FALSE
    )
    tmp <- tmp[!is.na(tmp$gene_id) & tmp$gene_id != "" & !is.na(tmp$gene_symbol) & tmp$gene_symbol != "", , drop = FALSE]
    tmp <- tmp[!duplicated(tmp$gene_id), , drop = FALSE]
    map_list[[length(map_list) + 1]] <- tmp
  }
  if (length(map_list) == 0) {
    return(data.frame(gene_id = character(0), gene_symbol = character(0), stringsAsFactors = FALSE))
  }
  out <- do.call(rbind, map_list)
  out <- out[!duplicated(out$gene_id), , drop = FALSE]
  rownames(out) <- NULL
  out
}


score_de_candidate <- function(file, contrast_tag) {
  bn <- tolower(basename(file))
  cols <- tryCatch(tolower(names(read.csv(file, nrows = 1, check.names = FALSE))), error = function(e) character(0))
  score <- 0
  if (grepl("qlf|edger|de", bn)) score <- score + 20
  if (grepl("trimmed|h2w6", bn)) score <- score + 10
  if (grepl(contrast_tag, bn)) score <- score + 30
  if (any(cols %in% c("logfc", "log2fc", "log2foldchange"))) score <- score + 20
  if (any(cols %in% c("pvalue", "p.value", "pval", "p.value.qlf", "p"))) score <- score + 20
  if (any(cols %in% c("gene_name", "gene_symbol", "symbol", "pig_symbol", "external_gene_name"))) score <- score + 10
  if (grepl("summary|stability|fgsea|gsea|ranked|count|matrix|manifest|sample|assignment|qc|status|overall|parameter|method", bn)) score <- score - 100
  score
}

find_trimmed_de_file <- function(contrast_tag) {
  # First try likely exact names. If not found, fall back to a scored recursive search.
  exact_candidates <- c(
    file.path(fastp_tables_dir, paste0("stepH2w6_trimmed_edgeR_QLF_DE_", contrast_tag, "_vs_CON.csv")),
    file.path(fastp_tables_dir, paste0("stepH2w6_trimmed_edgeR_QLF_", contrast_tag, "_vs_CON.csv")),
    file.path(fastp_tables_dir, paste0("stepH2w6_trimmed_DE_", contrast_tag, "_vs_CON_QLF.csv")),
    file.path(fastp_tables_dir, paste0("stepH2w6_trimmed_edgeR_QLF_DE_", contrast_tag, "_vs_Control.csv")),
    file.path(fastp_tables_dir, paste0("stepH2w6_trimmed_DE_", contrast_tag, "_vs_Control_QLF.csv"))
  )
  hit <- exact_candidates[file.exists(exact_candidates)]
  if (length(hit) > 0) return(normalizePath(hit[1], winslash = "/", mustWork = FALSE))

  files <- list.files(fastp_tables_dir, pattern = "\\.csv$", recursive = TRUE, full.names = TRUE)
  if (length(files) == 0) return(NA_character_)
  scores <- vapply(files, score_de_candidate, numeric(1), contrast_tag = contrast_tag)
  cand <- data.frame(file = normalizePath(files, winslash = "/", mustWork = FALSE),
                     basename = basename(files),
                     score = scores,
                     stringsAsFactors = FALSE)
  cand <- cand[order(-cand$score, cand$basename), , drop = FALSE]
  cand_file <- file.path(out_dir, paste0("stepH2w9_current78_trimmed_DE_candidates_", contrast_tag, ".csv"))
  write_csv(cand, cand_file)
  if (nrow(cand) == 0 || cand$score[1] < 60) {
    stop("Could not identify trimmed DE table for ", contrast_tag,
         ". Candidate list saved to: ", cand_file, call. = FALSE)
  }
  cand$file[1]
}

rank_one_table <- function(de_file, contrast_label, branch_label, symbol_map = NULL, hallmark_symbols = NULL) {
  df <- safe_read_csv(de_file)

  gene_id_col <- find_col(df, c("gene_id", "pig_ensg", "GeneID", "Geneid", "feature_id", "ensembl_gene_id"), TRUE, "gene id column")
  symbol_col <- find_col(df, c("gene_name", "gene_symbol", "SYMBOL", "symbol", "pig_symbol", "external_gene_name"), FALSE, "gene symbol column")
  logfc_col <- find_col(df, c("logFC", "LogFC", "log2FC", "log2FoldChange", "log2_fold_change"), TRUE, "logFC column")
  p_col <- find_col(df, c("PValue", "P.Value", "pvalue", "P.value", "PVAL", "P", "p"), TRUE, "P value column")
  fdr_col <- find_col(df, c("FDR", "adj.P.Val", "padj", "qvalue"), FALSE, "FDR column")

  gene_id <- clean_symbol(df[[gene_id_col]])

  # Current formal GSEA uses pig gene symbols. Some trimmed DE files contain only Ensembl IDs.
  # If symbol column is absent or does not overlap with Hallmark symbols, map Ensembl IDs to symbols
  # using the untrimmed DE annotation table.
  gene_symbol_from_file <- if (!is.na(symbol_col)) clean_symbol(df[[symbol_col]]) else rep(NA_character_, nrow(df))
  n_symbol_overlap_from_file <- if (!is.null(hallmark_symbols)) {
    length(intersect(unique(gene_symbol_from_file[!is.na(gene_symbol_from_file)]), hallmark_symbols))
  } else {
    NA_integer_
  }

  gene_symbol <- gene_symbol_from_file
  symbol_source <- if (!is.na(symbol_col)) paste0("file_column:", symbol_col) else "none"

  need_symbol_map <- is.na(symbol_col) ||
    all(is.na(gene_symbol_from_file)) ||
    (!is.null(hallmark_symbols) && !is.na(n_symbol_overlap_from_file) && n_symbol_overlap_from_file < 100)

  if (need_symbol_map && !is.null(symbol_map) && nrow(symbol_map) > 0) {
    mapped <- symbol_map$gene_symbol[match(gene_id, symbol_map$gene_id)]
    use_mapped <- !is.na(mapped) & mapped != ""
    gene_symbol[use_mapped] <- mapped[use_mapped]
    symbol_source <- paste0("mapped_from_gene_id_using_untrimmed_DE_annotation; original_symbol_overlap=", n_symbol_overlap_from_file)
  }

  # Do not fall back to Ensembl IDs for formal Hallmark GSEA, because msigdbr Hallmark is gene-symbol based here.
  logfc <- suppressWarnings(as.numeric(df[[logfc_col]]))
  pval <- safe_p(df[[p_col]])
  fdr <- if (!is.na(fdr_col)) suppressWarnings(as.numeric(df[[fdr_col]])) else rep(NA_real_, nrow(df))
  rank_stat <- sign(logfc) * (-log10(pval))

  rank_df <- data.frame(
    contrast = contrast_label,
    branch = branch_label,
    gene_id = gene_id,
    gene_symbol = gene_symbol,
    logFC = logfc,
    PValue = pval,
    FDR = fdr,
    rank_stat = rank_stat,
    stringsAsFactors = FALSE
  )

  keep <- !is.na(rank_df$gene_symbol) & rank_df$gene_symbol != "" &
    !is.na(rank_df$logFC) & !is.na(rank_df$PValue) & rank_df$PValue > 0 &
    !is.na(rank_df$rank_stat) & is.finite(rank_df$rank_stat)
  removed_invalid_rows <- sum(!keep)
  rank_df <- rank_df[keep, , drop = FALSE]

  if (!is.null(hallmark_symbols)) {
    n_symbol_overlap_final <- length(intersect(unique(rank_df$gene_symbol), hallmark_symbols))
  } else {
    n_symbol_overlap_final <- NA_integer_
  }

  ord <- order(-abs(rank_df$rank_stat), rank_df$gene_symbol)
  rank_df <- rank_df[ord, , drop = FALSE]
  duplicated_symbol_rows_removed <- sum(duplicated(rank_df$gene_symbol))
  rank_df <- rank_df[!duplicated(rank_df$gene_symbol), , drop = FALSE]
  rank_df <- rank_df[order(rank_df$rank_stat, decreasing = TRUE), , drop = FALSE]
  rownames(rank_df) <- NULL

  stats_vec <- rank_df$rank_stat
  names(stats_vec) <- rank_df$gene_symbol
  stats_vec <- sort(stats_vec, decreasing = TRUE)

  list(
    rank_df = rank_df,
    stats_vec = stats_vec,
    n_ranked_symbols = length(stats_vec),
    removed_invalid_rows = removed_invalid_rows,
    duplicated_symbol_rows_removed = duplicated_symbol_rows_removed,
    gene_id_col = gene_id_col,
    symbol_col = symbol_col,
    symbol_source = symbol_source,
    n_symbol_overlap_from_file = n_symbol_overlap_from_file,
    n_symbol_overlap_final = n_symbol_overlap_final,
    logfc_col = logfc_col,
    p_col = p_col,
    fdr_col = fdr_col
  )
}

clean_fgsea_out <- function(fgsea_result, contrast_label, branch_label) {
  out <- as.data.frame(fgsea_result, stringsAsFactors = FALSE)

  # If fgsea returns zero pathways, do not trigger "$<- data.frame" replacement errors.
  # Instead, return a well-formed empty result and let the caller stop with a clear diagnostic.
  if (nrow(out) == 0) {
    out <- data.frame(
      branch = character(0),
      contrast = character(0),
      pathway = character(0),
      pval = numeric(0),
      padj = numeric(0),
      log2err = numeric(0),
      ES = numeric(0),
      NES = numeric(0),
      size = integer(0),
      leadingEdge_size = integer(0),
      leadingEdge_genes = character(0),
      stringsAsFactors = FALSE
    )
    return(out)
  }

  if ("leadingEdge" %in% colnames(out)) {
    out$leadingEdge_size <- vapply(out$leadingEdge, length, integer(1))
    out$leadingEdge_genes <- vapply(out$leadingEdge, function(x) paste(x, collapse = ";"), character(1))
    out$leadingEdge <- NULL
  }
  out$contrast <- rep(contrast_label, nrow(out))
  out$branch <- rep(branch_label, nrow(out))
  out <- out[, c("branch", "contrast", setdiff(colnames(out), c("branch", "contrast"))), drop = FALSE]
  out
}

stability_label <- function(spearman_nes, max_abs_delta_target, target_direction_agreement) {
  if (is.na(spearman_nes)) return("needs_review")
  if (spearman_nes >= 0.98 && max_abs_delta_target <= 0.10 && isTRUE(target_direction_agreement)) return("highly_stable")
  if (spearman_nes >= 0.95 && max_abs_delta_target <= 0.20 && isTRUE(target_direction_agreement)) return("stable")
  if (spearman_nes >= 0.90 && max_abs_delta_target <= 0.35) return("mostly_stable")
  "needs_review"
}

## =========================
## 2. Input DE files
## =========================

untrimmed_t7_file <- file.path(main_tables_dir, "step17_pig_early_DE_t7_vs_CON_QLF.csv")
untrimmed_t28_file <- file.path(main_tables_dir, "step17_pig_early_DE_t28_vs_CON_QLF.csv")
trimmed_t7_file <- file.path(fastp_tables_dir, "stepH2w6_trimmed_DE_ACLT_t7_vs_Control_t0_QLF.csv")
trimmed_t28_file <- file.path(fastp_tables_dir, "stepH2w6_trimmed_DE_ACLT_t28_vs_Control_t0_QLF.csv")

stop_if_missing(untrimmed_t7_file, "untrimmed t7 QLF DE table")
stop_if_missing(untrimmed_t28_file, "untrimmed t28 QLF DE table")
stop_if_missing(trimmed_t7_file, "trimmed t7 QLF DE table")
stop_if_missing(trimmed_t28_file, "trimmed t28 QLF DE table")

de_files <- data.frame(
  branch = c("untrimmed", "untrimmed", "trimmed", "trimmed"),
  contrast = c("ACLT_untreated_t7_vs_Control", "ACLT_untreated_t28_vs_Control",
               "ACLT_untreated_t7_vs_Control", "ACLT_untreated_t28_vs_Control"),
  timepoint = c("t7", "t28", "t7", "t28"),
  de_file = c(untrimmed_t7_file, untrimmed_t28_file, trimmed_t7_file, trimmed_t28_file),
  selection_mode = "locked_exact_path_no_recursive_search",
  stringsAsFactors = FALSE
)

selected_de_file <- file.path(out_dir, "stepH2w9_current78_selected_DE_files.csv")
write_csv(de_files, selected_de_file)

cat("Selected DE files:\n")
print(de_files)

## =========================
## 3A. Load Sus scrofa Hallmark gene sets before ranking
## =========================

msig_df <- tryCatch(
  msigdbr::msigdbr(species = "Sus scrofa", collection = "H"),
  error = function(e) msigdbr::msigdbr(species = "Sus scrofa", category = "H")
)

if (nrow(msig_df) == 0) stop("msigdbr returned no Sus scrofa Hallmark gene sets.", call. = FALSE)

pathway_col <- find_col(msig_df, c("gs_name", "gs_exact_source"), TRUE, "MSigDB pathway column")
gene_col <- find_col(msig_df, c("gene_symbol", "db_gene_symbol"), TRUE, "MSigDB gene symbol column")

hallmark_members <- data.frame(
  pathway = as.character(msig_df[[pathway_col]]),
  gene_symbol = as.character(msig_df[[gene_col]]),
  stringsAsFactors = FALSE
)
hallmark_members <- hallmark_members[!is.na(hallmark_members$pathway) & !is.na(hallmark_members$gene_symbol) &
                                       hallmark_members$pathway != "" & hallmark_members$gene_symbol != "", , drop = FALSE]
hallmark_members <- unique(hallmark_members)

pathways <- split(hallmark_members$gene_symbol, hallmark_members$pathway)
pathways <- lapply(pathways, unique)
pathways <- pathways[order(names(pathways))]
hallmark_symbols <- unique(hallmark_members$gene_symbol)

fgsea_minSize <- 10
fgsea_maxSize <- 500
fgsea_eps <- 0
fgsea_nproc <- 1

target_pathways <- c(
  "HALLMARK_INFLAMMATORY_RESPONSE",
  "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"
)

missing_targets <- setdiff(target_pathways, names(pathways))
if (length(missing_targets) > 0) {
  stop("Target Hallmark pathways missing from Sus scrofa Hallmark collection: ", paste(missing_targets, collapse = ", "), call. = FALSE)
}

symbol_map <- build_symbol_map_from_de_files(c(untrimmed_t7_file, untrimmed_t28_file))
symbol_map_file <- file.path(out_dir, "stepH2w9_current78_gene_id_to_symbol_map_from_untrimmed_DE.csv")
write_csv(symbol_map, symbol_map_file)

cat("Hallmark gene sets loaded: ", length(pathways), "\n", sep = "")
cat("Unique Hallmark symbols: ", length(hallmark_symbols), "\n", sep = "")
cat("Gene ID -> symbol map rows from untrimmed DE: ", nrow(symbol_map), "\n", sep = "")
cat("fgsea parameters: minSize=", fgsea_minSize, ", maxSize=", fgsea_maxSize, ", eps=", fgsea_eps, ", nproc=", fgsea_nproc, "\n\n", sep = "")

## =========================
## 3. Ranked gene lists
## =========================

ranked_objects <- list()
ranked_summary_list <- list()

for (i in seq_len(nrow(de_files))) {
  key <- paste(de_files$branch[i], de_files$timepoint[i], sep = "__")
  ranked_objects[[key]] <- rank_one_table(
    de_file = de_files$de_file[i],
    contrast_label = de_files$contrast[i],
    branch_label = de_files$branch[i],
    symbol_map = symbol_map,
    hallmark_symbols = hallmark_symbols
  )
  ro <- ranked_objects[[key]]
  ranked_summary_list[[length(ranked_summary_list) + 1]] <- data.frame(
    branch = de_files$branch[i],
    contrast = de_files$contrast[i],
    timepoint = de_files$timepoint[i],
    de_file = de_files$de_file[i],
    gene_id_col = ro$gene_id_col,
    symbol_col = ro$symbol_col,
    symbol_source = ro$symbol_source,
    n_symbol_overlap_from_file = ro$n_symbol_overlap_from_file,
    n_symbol_overlap_final = ro$n_symbol_overlap_final,
    logfc_col = ro$logfc_col,
    p_col = ro$p_col,
    fdr_col = ro$fdr_col,
    n_ranked_symbols = ro$n_ranked_symbols,
    removed_invalid_rows = ro$removed_invalid_rows,
    duplicated_symbol_rows_removed = ro$duplicated_symbol_rows_removed,
    min_rank_stat = min(ro$stats_vec, na.rm = TRUE),
    max_rank_stat = max(ro$stats_vec, na.rm = TRUE),
    stringsAsFactors = FALSE
  )
}

ranked_summary <- do.call(rbind, ranked_summary_list)
ranked_summary_file <- file.path(out_dir, "stepH2w9_current78_ranked_gene_summary.csv")
write_csv(ranked_summary, ranked_summary_file)

# Save ranked lists for reproducibility
for (nm in names(ranked_objects)) {
  outfile <- file.path(out_dir, paste0("stepH2w9_current78_ranked_genes_", nm, ".csv"))
  write_csv(ranked_objects[[nm]]$rank_df, outfile)
}

## =========================
## 4. Sus scrofa Hallmark gene sets
## =========================
# Hallmark gene sets were loaded before ranking to allow symbol-overlap diagnostics.

pathway_source_summary <- data.frame(
  source = "msigdbr",
  species = "Sus scrofa",
  collection = "MSigDB Hallmark collection H",
  pathway_col = pathway_col,
  gene_col_used = gene_col,
  n_full_hallmark_gene_sets_loaded = length(pathways),
  fgsea_minSize = fgsea_minSize,
  fgsea_maxSize = fgsea_maxSize,
  fgsea_eps = fgsea_eps,
  fgsea_nproc = fgsea_nproc,
  target_pathways = paste(target_pathways, collapse = "; "),
  full_collection_FDR_used = TRUE,
  gene_identifier_for_GSEA = "pig gene symbols; trimmed DE Ensembl IDs mapped to symbols using untrimmed DE annotation if needed",
  stringsAsFactors = FALSE
)
pathway_source_file <- file.path(out_dir, "stepH2w9_current78_pathway_source_and_parameters.csv")
write_csv(pathway_source_summary, pathway_source_file)

coverage_list <- list()
for (nm in names(ranked_objects)) {
  stats_vec <- ranked_objects[[nm]]$stats_vec
  parts <- strsplit(nm, "__", fixed = TRUE)[[1]]
  coverage_list[[length(coverage_list) + 1]] <- data.frame(
    branch = parts[1],
    timepoint = parts[2],
    pathway = names(pathways),
    n_genes_in_pathway = vapply(pathways, length, integer(1)),
    n_genes_present_in_rank = vapply(pathways, function(gs) sum(gs %in% names(stats_vec)), integer(1)),
    stringsAsFactors = FALSE
  )
}
coverage_df <- do.call(rbind, coverage_list)
coverage_file <- file.path(out_dir, "stepH2w9_current78_hallmark_coverage_by_branch.csv")
write_csv(coverage_df, coverage_file)

saveRDS(pathways, file.path(obj_dir, "stepH2w9_current78_sus_scrofa_hallmark_pathways.rds"))

## =========================
## 5. Run fgsea on full Hallmark collection
## =========================

fgsea_results <- list()

for (nm in names(ranked_objects)) {
  parts <- strsplit(nm, "__", fixed = TRUE)[[1]]
  branch <- parts[1]
  timepoint <- parts[2]
  contrast_label <- de_files$contrast[de_files$branch == branch & de_files$timepoint == timepoint][1]

  stats_vec <- ranked_objects[[nm]]$stats_vec
  pathway_overlap_n <- vapply(pathways, function(gs) sum(gs %in% names(stats_vec)), integer(1))
  n_pathways_passing_size <- sum(pathway_overlap_n >= fgsea_minSize & pathway_overlap_n <= fgsea_maxSize)

  cat("Running fgsea for ", nm, ": ranked symbols=", length(stats_vec),
      ", pathways passing size filter=", n_pathways_passing_size, "\n", sep = "")

  if (n_pathways_passing_size == 0) {
    diag_file <- file.path(out_dir, paste0("stepH2w9_current78_no_pathways_passing_size_filter_", nm, ".csv"))
    diag_df <- data.frame(
      pathway = names(pathways),
      n_genes_in_pathway = vapply(pathways, length, integer(1)),
      n_genes_present_in_rank = pathway_overlap_n,
      stringsAsFactors = FALSE
    )
    write_csv(diag_df, diag_file)
    stop("No Hallmark pathways passed fgsea size filtering for ", nm,
         ". This usually means the ranked gene identifiers do not match msigdbr gene symbols, or the wrong DE file was selected. Diagnostic saved to: ",
         diag_file, call. = FALSE)
  }

  set.seed(1)
  res <- fgsea::fgsea(
    pathways = pathways,
    stats = stats_vec,
    minSize = fgsea_minSize,
    maxSize = fgsea_maxSize,
    eps = fgsea_eps,
    nproc = fgsea_nproc
  )

  if (nrow(as.data.frame(res)) == 0) {
    diag_file <- file.path(out_dir, paste0("stepH2w9_current78_fgsea_returned_zero_rows_", nm, ".csv"))
    diag_df <- data.frame(
      pathway = names(pathways),
      n_genes_in_pathway = vapply(pathways, length, integer(1)),
      n_genes_present_in_rank = pathway_overlap_n,
      passes_size_filter = pathway_overlap_n >= fgsea_minSize & pathway_overlap_n <= fgsea_maxSize,
      stringsAsFactors = FALSE
    )
    write_csv(diag_df, diag_file)
    stop("fgsea returned zero rows for ", nm,
         " despite pathway overlap checks. Diagnostic saved to: ", diag_file, call. = FALSE)
  }

  fgsea_results[[nm]] <- clean_fgsea_out(res, contrast_label, branch)
}

fgsea_all <- do.call(rbind, fgsea_results)
fgsea_all <- fgsea_all[order(fgsea_all$contrast, fgsea_all$branch, fgsea_all$padj), , drop = FALSE]

fgsea_all_file <- file.path(out_dir, "stepH2w9_current78_fgsea_full_hallmark_all_branches.csv")
write_csv(fgsea_all, fgsea_all_file)

target_results <- fgsea_all[fgsea_all$pathway %in% target_pathways, , drop = FALSE]
target_results <- target_results[order(target_results$contrast, target_results$pathway, target_results$branch), , drop = FALSE]
target_results_file <- file.path(out_dir, "stepH2w9_current78_target_pathway_results_all_branches.csv")
write_csv(target_results, target_results_file)

## =========================
## 6. Stability comparison
## =========================

comparison_list <- list()
target_comparison_list <- list()

for (tp in c("t7", "t28")) {
  contrast_label <- de_files$contrast[de_files$timepoint == tp][1]
  u <- fgsea_all[fgsea_all$contrast == contrast_label & fgsea_all$branch == "untrimmed", , drop = FALSE]
  t <- fgsea_all[fgsea_all$contrast == contrast_label & fgsea_all$branch == "trimmed", , drop = FALSE]

  m <- merge(
    u[, c("pathway", "NES", "pval", "padj", "size")],
    t[, c("pathway", "NES", "pval", "padj", "size")],
    by = "pathway",
    suffixes = c("_untrimmed", "_trimmed")
  )
  m$contrast <- contrast_label
  m$timepoint <- tp
  m$delta_NES <- m$NES_trimmed - m$NES_untrimmed
  m$abs_delta_NES <- abs(m$delta_NES)
  m$direction_same <- sign(m$NES_untrimmed) == sign(m$NES_trimmed)
  m$is_target <- m$pathway %in% target_pathways

  comparison_list[[tp]] <- m
  target_comparison_list[[tp]] <- m[m$is_target, , drop = FALSE]
}

comparison_all <- do.call(rbind, comparison_list)
comparison_all <- comparison_all[order(comparison_all$timepoint, comparison_all$is_target, comparison_all$pathway), , drop = FALSE]
comparison_file <- file.path(out_dir, "stepH2w9_current78_GSEA_trimmed_vs_untrimmed_all_common_pathways.csv")
write_csv(comparison_all, comparison_file)

target_comparison <- do.call(rbind, target_comparison_list)
target_comparison <- target_comparison[order(target_comparison$timepoint, target_comparison$pathway), , drop = FALSE]
target_comparison_file <- file.path(out_dir, "stepH2w9_current78_GSEA_target_pathways_stability.csv")
write_csv(target_comparison, target_comparison_file)

summary_by_contrast <- do.call(rbind, lapply(split(comparison_all, comparison_all$timepoint), function(x) {
  tx <- x[x$is_target, , drop = FALSE]
  spearman_nes <- suppressWarnings(cor(x$NES_untrimmed, x$NES_trimmed, method = "spearman", use = "complete.obs"))
  pearson_nes <- suppressWarnings(cor(x$NES_untrimmed, x$NES_trimmed, method = "pearson", use = "complete.obs"))
  target_direction_agreement <- nrow(tx) == length(target_pathways) && all(tx$direction_same, na.rm = TRUE)
  max_abs_delta_target <- if (nrow(tx) > 0) max(tx$abs_delta_NES, na.rm = TRUE) else NA_real_

  data.frame(
    timepoint = unique(x$timepoint),
    contrast = unique(x$contrast),
    n_common_pathways = nrow(x),
    spearman_NES_all_common_pathways = spearman_nes,
    pearson_NES_all_common_pathways = pearson_nes,
    max_abs_delta_NES_all_common_pathways = max(x$abs_delta_NES, na.rm = TRUE),
    mean_abs_delta_NES_all_common_pathways = mean(x$abs_delta_NES, na.rm = TRUE),
    n_target_pathways = nrow(tx),
    max_abs_delta_NES_target_pathways = max_abs_delta_target,
    target_direction_agreement = target_direction_agreement,
    target_pathways_all_found = nrow(tx) == length(target_pathways),
    stability_flag = stability_label(spearman_nes, max_abs_delta_target, target_direction_agreement),
    stringsAsFactors = FALSE
  )
}))
summary_by_contrast <- summary_by_contrast[order(summary_by_contrast$timepoint), , drop = FALSE]
summary_by_contrast_file <- file.path(out_dir, "stepH2w9_current78_GSEA_stability_summary_by_timepoint.csv")
write_csv(summary_by_contrast, summary_by_contrast_file)

min_spearman <- min(summary_by_contrast$spearman_NES_all_common_pathways, na.rm = TRUE)
max_delta_target <- max(summary_by_contrast$max_abs_delta_NES_target_pathways, na.rm = TRUE)
target_agree_all <- all(summary_by_contrast$target_direction_agreement)
target_found_all <- all(summary_by_contrast$target_pathways_all_found)
overall_stability_flag <- stability_label(min_spearman, max_delta_target, target_agree_all && target_found_all)

## =========================
## 7. Stability plots
## =========================

scatter_df <- comparison_all
scatter_df$timepoint_label <- ifelse(scatter_df$timepoint == "t7", "ACLT-untreated-1W", "ACLT-untreated-4W")
scatter_df$target_label <- ifelse(scatter_df$is_target, "Prespecified target", "Other Hallmark")

p_all <- ggplot(scatter_df, aes(x = NES_untrimmed, y = NES_trimmed)) +
  geom_point(aes(shape = target_label), size = 2.2, alpha = 0.85) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "grey45") +
  facet_wrap(~ timepoint_label, nrow = 1) +
  labs(
    title = "Hallmark GSEA NES stability after fastp trimming",
    x = "Untrimmed NES",
    y = "Trimmed NES",
    shape = NULL
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    strip.text = element_text(face = "bold")
  )

plot_png <- file.path(fig_dir, "stepH2w9_current78_GSEA_NES_trimmed_vs_untrimmed_scatter.png")
plot_pdf <- file.path(fig_dir, "stepH2w9_current78_GSEA_NES_trimmed_vs_untrimmed_scatter.pdf")
png(plot_png, width = 2400, height = 1100, res = 250)
print(p_all)
dev.off()
pdf(plot_pdf, width = 9.6, height = 4.4)
print(p_all)
dev.off()

## =========================
## 8. Save summary and method records
## =========================

version_df <- data.frame(
  item = c(
    "R_version",
    "fgsea_package_version",
    "msigdbr_package_version",
    "ggplot2_package_version",
    "dplyr_package_version",
    "msigdbr_species",
    "msigdbr_collection",
    "fgsea_minSize",
    "fgsea_maxSize",
    "fgsea_eps",
    "fgsea_nproc",
    "rank_statistic",
    "gene_identifier_for_GSEA",
    "target_pathways_note",
    "branch_role"
  ),
  value = c(
    as.character(getRversion()),
    as.character(utils::packageVersion("fgsea")),
    as.character(utils::packageVersion("msigdbr")),
    as.character(utils::packageVersion("ggplot2")),
    as.character(utils::packageVersion("dplyr")),
    "Sus scrofa",
    "MSigDB Hallmark collection H",
    fgsea_minSize,
    fgsea_maxSize,
    fgsea_eps,
    fgsea_nproc,
    "sign(logFC) * -log10(PValue)",
    "pig gene symbols, matching current Step20_current78",
    "fgsea was run on the full Hallmark collection; target pathways were extracted afterward",
    "fastp trimming sensitivity analysis, not replacement for main untrimmed analysis"
  ),
  stringsAsFactors = FALSE
)
version_file <- file.path(out_dir, "stepH2w9_current78_versions_and_method_records.csv")
write_csv(version_df, version_file)

overall_summary <- data.frame(
  metric = c(
    "untrimmed_t7_DE_file",
    "untrimmed_t28_DE_file",
    "trimmed_t7_DE_file",
    "trimmed_t28_DE_file",
    "n_full_hallmark_gene_sets_loaded",
    "n_fgsea_pathways_untrimmed_t7",
    "n_fgsea_pathways_untrimmed_t28",
    "n_fgsea_pathways_trimmed_t7",
    "n_fgsea_pathways_trimmed_t28",
    "fgsea_minSize",
    "fgsea_maxSize",
    "fgsea_eps",
    "rank_statistic",
    "gene_identifier_for_GSEA",
    "full_collection_FDR_used",
    "target_pathways",
    "min_spearman_NES_all_common_pathways",
    "max_abs_delta_NES_target_pathways",
    "target_direction_agreement_all_contrasts",
    "target_pathways_all_found_all_contrasts",
    "overall_stability_flag",
    "selected_de_file",
    "symbol_map_file",
    "ranked_summary_file",
    "fgsea_all_file",
    "comparison_file",
    "target_comparison_file",
    "summary_by_timepoint_file",
    "plot_png",
    "plot_pdf",
    "output_dir"
  ),
  value = c(
    untrimmed_t7_file,
    untrimmed_t28_file,
    trimmed_t7_file,
    trimmed_t28_file,
    length(pathways),
    nrow(fgsea_all[fgsea_all$branch == "untrimmed" & fgsea_all$contrast == "ACLT_untreated_t7_vs_Control", , drop = FALSE]),
    nrow(fgsea_all[fgsea_all$branch == "untrimmed" & fgsea_all$contrast == "ACLT_untreated_t28_vs_Control", , drop = FALSE]),
    nrow(fgsea_all[fgsea_all$branch == "trimmed" & fgsea_all$contrast == "ACLT_untreated_t7_vs_Control", , drop = FALSE]),
    nrow(fgsea_all[fgsea_all$branch == "trimmed" & fgsea_all$contrast == "ACLT_untreated_t28_vs_Control", , drop = FALSE]),
    fgsea_minSize,
    fgsea_maxSize,
    fgsea_eps,
    "sign(logFC) * -log10(PValue)",
    "pig gene symbols",
    TRUE,
    paste(target_pathways, collapse = "; "),
    round(min_spearman, 6),
    round(max_delta_target, 6),
    target_agree_all,
    target_found_all,
    overall_stability_flag,
    selected_de_file,
    symbol_map_file,
    ranked_summary_file,
    fgsea_all_file,
    comparison_file,
    target_comparison_file,
    summary_by_contrast_file,
    plot_png,
    plot_pdf,
    out_dir
  ),
  stringsAsFactors = FALSE
)

overall_summary_file <- file.path(out_dir, "stepH2w9_current78_GSEA_stability_overall_summary.csv")
write_csv(overall_summary, overall_summary_file)

saveRDS(
  list(
    de_files = de_files,
    ranked_summary = ranked_summary,
    pathways = pathways,
    fgsea_all = fgsea_all,
    comparison_all = comparison_all,
    target_comparison = target_comparison,
    summary_by_contrast = summary_by_contrast,
    overall_summary = overall_summary,
    version_df = version_df
  ),
  file.path(obj_dir, "stepH2w9_current78_GSEA_stability_workspace.rds")
)

writeLines(capture.output(sessionInfo()), file.path(out_dir, "stepH2w9_current78_sessionInfo.txt"))

cat("\n===== StepH2w9_current78 overall summary =====\n")
print(overall_summary, row.names = FALSE)

cat("\n===== StepH2w9_current78 summary by timepoint =====\n")
print(summary_by_contrast, row.names = FALSE)

cat("\n===== StepH2w9_current78 target pathway comparison =====\n")
print(target_comparison[, c(
  "timepoint", "pathway", "NES_untrimmed", "NES_trimmed", "delta_NES",
  "padj_untrimmed", "padj_trimmed", "direction_same"
)], row.names = FALSE)

cat("\n===== Version and method records =====\n")
print(version_df, row.names = FALSE)

cat("\nStepH2w9_current78 completed.\n")

summary_con <- file(summary_log_file, open = "wt")
writeLines("===== StepH2w9_current78 GSEA stability SUMMARY TO SEND ME =====", summary_con)
writeLines(paste0("Run time: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S")), summary_con)
writeLines("", summary_con)
writeLines("Main run summary:", summary_con)
writeLines(capture.output(print(overall_summary, row.names = FALSE)), summary_con)
writeLines("", summary_con)
writeLines("GSEA stability summary by timepoint:", summary_con)
writeLines(capture.output(print(summary_by_contrast, row.names = FALSE)), summary_con)
writeLines("", summary_con)
writeLines("Target pathway comparison:", summary_con)
writeLines(capture.output(print(target_comparison[, c(
  "timepoint", "pathway", "NES_untrimmed", "NES_trimmed", "delta_NES",
  "padj_untrimmed", "padj_trimmed", "direction_same"
)], row.names = FALSE)), summary_con)
writeLines("", summary_con)
writeLines("Version and method records:", summary_con)
writeLines(capture.output(print(version_df, row.names = FALSE)), summary_con)
writeLines("", summary_con)
writeLines("Interpretation checkpoint:", summary_con)
writeLines("Please verify that fgsea was run on the full Sus scrofa Hallmark collection with minSize=10, maxSize=500, eps=0, nproc=1.", summary_con)
writeLines("Please verify that target pathway FDR values are from the full collection-level analysis.", summary_con)
writeLines("The main stability metrics are Spearman correlation of NES across all common Hallmark pathways and max |delta NES| for the two prespecified target pathways.", summary_con)
close(summary_con)

sink()

cat("\nStepH2w9_current78 GSEA stability completed.\n")
cat("Summary to send me: ", summary_log_file, "\n", sep = "")
